### ISSUE TITLE
Custom MultiFieldQueryParser

### ISSUE THREAD

**Issue by cmwalolo** [Shazwazza/Examine#106]
Would it be possible to inject a custom MultiFieldQueryParser .
Our issue is that we have created a custom Analyzer to Normalize strings, but when doing a search
the queryparser do not normalize the keywords when using fuzzy or wildcard searches. In later versions of Lucene.Net it can be solved by using the AnalyzingQueryParser.cs.

I did a test of implementation of a CustomMultiFieldQueryParser which seems to work well within Examine. It would be great if we could inject in the LuceneCriteriaSearch class.

**Comment by Shazwazza** [comment]
What version of Umbraco are you using?
