### ISSUE TITLE
Random crashes of w3wp on indexing nodes.

### ISSUE THREAD

**Issue by eriksimonic** [Shazwazza/Examine#107]
Hi. I am experiencing this issue, and I can't make any sense of it.
I am using Umbaco 7.10.4, Merchello 2.6. Everything works but sometimes the w3wp logs this event, and the most interesting line is Debugger.Debu, see the screenshot. 
Examine is latest version available through NuGet.

Any ideas?

![image](https://user-images.githubusercontent.com/10416737/48552732-d5f5c080-e8d9-11e8-8f57-535c51ae0beb.png)

**Comment by Shazwazza** [comment]
Without being able to replicate this there's not a lot I'll be able to help out with. If you can replicate with a normal Umbraco install without any other plugins like Merchello at least it gives an idea that it's not a plugin issue.

**Comment by Shazwazza** [comment]
That sounds like the cause then. Any exception thrown on a background thread will kill the server, you have to make sure you catch any/all exceptions when performing things on a background thread. Not sure exactly what you are doing but if you wrap the whole thing in a try/catch you can probably find out what the stack trace says.

**Comment by eriksimonic** [comment]
It seems that I "fixed" the problem by wrapping the error in try catch, still trying to get to the bottom of the problem. It only happens in a production environment.

Thanks for the help.

**Comment by Shazwazza** [comment]
When you have a chance i'd love to know the root cause. Thanks!
