### ISSUE TITLE
Errors delete index when deploying to Elastic beanstalk.

### ISSUE THREAD

**Issue by MidnightLady** [Shazwazza/Examine#108]
![untitled](https://user-images.githubusercontent.com/12786700/48627920-720ded80-e9e8-11e8-94a3-447eb83e0d03.png)
I can't deploy to EB because it's can't delete index files.
Any ideas? Thank you.

**Comment by Shazwazza** [comment]
Assuming this is an Umbraco site. I've never used EB so not really sure, only doc i've seen in the past about that is here https://aws.amazon.com/blogs/devops/run-umbraco-cms-with-flexible-load-balancing-on-aws/ 

Might be worth asking on our.umbraco.com forum to see if others are using EB, it's probably a configuration thing.
