### ISSUE TITLE
ExamineManager not unregistered from HostingEnvironment

### ISSUE THREAD

**Issue by benjaminc** [Shazwazza/Examine#113]
Calling the ExamineManager.DisableDefaultHostingEnvironmentRegistration method is supposed to prevent the ExamineManager object from being registered in the hosting environment, however the act of calling the method first initializes all static fields, which means the Instance field is initialized.  This initialization causes the constructor to be called while the _defaultRegisteration flag is still set to true.  As a result, the object is registered in the hosting environment.  The call to DisableDefaultHostingEnvironmentRegistration is then processed, setting the flag to false, and so when the Stop method is called, the ExamineManager doesn't unregister itself properly.

**Comment by Shazwazza** [comment]
now in release https://github.com/Shazwazza/Examine/releases/tag/v0.1.90
