### ISSUE TITLE
AzureDirectoryFactory - Lucene still lock after compete indexing

### ISSUE THREAD

**Issue by Michael-Artlist** [Shazwazza/Examine#115]
I'm using examine on azure with AzureDirectoryFactory.
After I run The Index Proccess its remain locked,
throwing Lucene.Net.Store.LockObtainFailedException: Lock obtain timed out:

**Comment by Shazwazza** [comment]
I need more info - what version of Examine are you using? Where did you find AzureDirectoryFactory since this isn't officially released? Do you have steps to replicate?

**Comment by Michael-Artlist** [comment]
It's from your repo (examine),i'm using it.
The steps are very simple im running the rebuildindex method when it's done it remain lock if i want to write something after it throws Lucene.Net.Store.LockObtainFailedException.

**Comment by Shazwazza** [comment]
Are you running this with Umbraco or on a standalone website? Can you provide more info, like are you load balancing/scaling/etc...

**Comment by mkariti2** [comment]
Hi @Shazwazza,
We are running in as a standalone on an mvc 5 website. 
It is on an azure webapp with autoscale enabled and slot integration.

**Comment by Shazwazza** [comment]
Having auto-scaled enabled with this setup will cause problems unless you have 2x azure app services configured - one for the master and one for the replicas. You can only enable auto-scale on the readonly ones. 

This is exactly also how Umbraco needs to be configured for auto-scale. There's a good chance you are running a write operation on a server that shouldn't be writing. Only a single instance can write to the indexes. See the docs about master/front-end servers: https://github.com/Shazwazza/Examine/wiki/Examine-with-Azure-Directory-(Blob-Storage)#to-set-this-up . If you have auto-scaled enabled, that entire app service will be readonly and you will need another one configured as master without auto-scale to work.
