### ISSUE TITLE
Wire Examine events before indexing starts 

### ISSUE THREAD

**Issue by hidarikani** [Shazwazza/Examine#118]
I've implemented `IApplicationEventHandler` and added Examine events to `OnApplicationStarted`. I then delete the `App_Data` folder and restart the app. When `OnApplicationStarted` fires all indexes have already been generated. My event handlers never execute. I've tried to add the event handlers to `OnApplicationInitialized` and  `OnApplicationStarting` but `ExamineManager` throws an exception.

Question: **ho do I wire the event handlers sooner, before the indexing starts?**

This is how I'm adding the event handler: ` ExamineManager.Instance.IndexProviderCollection["MyIndexer"].NodeIndexing += MyIndexingHandler;`

I'm refactoring an old app that runs v6.2.1

**Comment by Shazwazza** [comment]
This is an Umbraco question, not really an Examine question. You might have better luck asking on the umbraco forum: https://our.umbraco.com

6.2.1 is *very* old and really not supported anymore, I can't even remember how the Umbraco code in that version integrates with Examine. You best chance of finding out is to clone the Umbraco source and update to that very old branch and have a look at the guts of the code to see what is going on.
