### ISSUE TITLE
Searching by related content

### ISSUE THREAD

**Issue by CodeCheetah** [Shazwazza/Examine#119]
Hi,

How can I search related content (Multinode Picker)? The property value has a udi reference with the actual text value (title) entered in the referenced node.

Thanks.

**Comment by Shazwazza** [comment]
I would recommend you post this question on the Umbraco forum our.umbraco.com, there will be plenty more people to help you out. There's probably a number of different ways to do that such as using the `TransformingIndexValues` (depending on the version you are using).
