### ISSUE TITLE
Need to make the config abstract so it can be mocked or overridden or replaced

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#12]
Currently it's very strongly tied to the config file, we need to abstract this out somehow, at least make it replaceable so that we can configure it outside of a web app

**Comment by oheightoneninetwo** [comment]
Hi Shazwazza, is Examine not configurable outside of Web Applications? Are there any updates on this?

**Comment by Shazwazza** [comment]
@oheightoneninetwo I don't really understand your question. Examine is configurable anywhere you want it to be. The point of this issue was that the configuration classes were not abstracted in interfaces so you couldn't mock or test them. 

This is all resolved in 1.0 since there is no configuration classes at all, everything is initialized in code.
