### ISSUE TITLE
Unable to access searchers by their name in Umbraco 8

### ISSUE THREAD

**Issue by vidyesh-phases** [Shazwazza/Examine#120]
Unable to call the method to fetch a particular searcher using the following method in Umbraco 8:

`var externalSearcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
`

It says _'IExamineManager' does not contain a definition for 'SearchProviderCollection'_
Examine version: 1.0.0.0

**Comment by Shazwazza** [comment]
The APIs in the new Examine are different. I still need to find time to document them. In the meantime you can have a browse through the source - either the test project or the web test project to see how things are done.

**Comment by vidyesh-phases** [comment]
Thank you, Shaz. Looking forward to the updated documentation.

Solution:
`var examineSearcher = _examineManager.TryGetIndex("ExternalIndex", out var externalIndex) ? externalIndex.GetSearcher() : null;`
