### ISSUE TITLE
Question - Searching for a month in a date field

### ISSUE THREAD

**Issue by NikRimington** [Shazwazza/Examine#122]
Hey @Shazwazza ,

I was wondering, if you had a field called `newsDate` that is, as the name suggests, a date field on a document type and you want to find all entries in an index where the `newsDate` contains a specific month, any recommendations on how best to achieve this?

Or would you handle in indexing and and add a "month" and "year" field to the index to search on that specifically?

Nik

**Comment by Shazwazza** [comment]
There's probably a few ways to do it. Side note - There's different ways to index date data depending on the precision you want, see https://github.com/Shazwazza/Examine/blob/864168c7f019908242dd56197e075edea5ee77cf/src/Examine/FieldDefinitionTypes.cs#L16

If you literally want to do a search like "2" to return all data from February regardless of the year, then you will prob need to create a custom field in your index like `newsDate_month` and store the number. But if you did care about the year, then you would probably just store `newsDate` as a date type and then use a date query for the entire month and year(s) you are looking for. There's some examples in the test for date ranges https://github.com/Shazwazza/Examine/blob/864168c7f019908242dd56197e075edea5ee77cf/src/Examine/FieldDefinitionTypes.cs#L16, https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1555
