### ISSUE TITLE
Could not load type 'Lucene.Net.Analysis.Standard.StandardAnalizer' from assembly 'Lucene.Net'

### ISSUE THREAD

**Issue by rgdagostino** [Shazwazza/Examine#123]
Hello,
I've been stuck on this issue for more than 2 days now: 
I'm trying to add custom indexing to an umbraco website so the search can reach some external data from a db. It doesn't like my Examine Index Provider I setup in ExamineSettings.config. 

The error I get is “Could not load type 'Lucene.Net.Analysis.Standard.StandardAnalizer' from assembly 'Lucene.Net'.” 

Considering that I triple checked that the Lucene.Net assembly in the bin directory is the right one and includes that analyzer, I don't understand why I get the below error:

<img width="571" alt="examinerror" src="https://user-images.githubusercontent.com/8196233/58450749-89762200-8153-11e9-8150-8677a13eda46.png">

Other details: Lucene.Net (2.9.4.1), UmbracoCMS (7.13.2), .Net Framework 4.7.2

This is my index provider setup:

`<add name="My_Panel_Indexer"
           type="Examine.LuceneEngine.Providers.MultiIndexSearcher , Examine"
           indexSet="My_Panel_IndexSet"
           dataService="MyWebsite.BusinessLogic.DetachedBipadPanelIndex, MyWebsite.BusinessLogic" 
           analyzer="Lucene.Net.Analysis.Standard.StandardAnalizer, Lucene.Net"
           indexTypes="MyWebsite_PanelContentType" 
           runasync="true" />`

Did anybody go through this and could tell me where the issue is?
Thank you.
Giampiero

**Comment by robertjf** [comment]
never mind, found a typo in the ExamineSettings.config.  this issue can be closed :)
