### ISSUE TITLE
NestedQuery Conditional Operations?

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/Examine#129]
```
string[] documentTypes = { };

IBooleanOperation queryNodes = searchCriteria.Group(
            e => e.GroupedOr(new string[] { "hideFromSearch" }, "0")
            .And().GroupedOr(new string[] { "__NodeTypeAlias" }.ToList(), documentTypes)
            .And().GroupedOr(new[] { "nodeName", "id" }.ToList(), new string[] { "Network - Marine Conservation" })
            );
```

Any ideas on how I can make the __NodeTypeAlias conditional on documentTypes having at least one value in this grouped query?
Presently if it's empty the query ends up with a +() in the raw lucene string, and thus nothing is found, rather than if empty allow all nodeType aliases.

**Comment by Shazwazza** [comment]
I think you could do something like this - this is untested so the syntax might not be exact but should give you an idea.  Group receives a `Func` so you can put logic within the lambda and return what you want.

```cs
IBooleanOperation queryNodes = searchCriteria.Group(
            e => {
                  var qry = e.Field("hideFromSearch", "0");
                  if (documentTypes.Count > 0) {
                        qry = qry.And().GroupedOr(new string[] { "__NodeTypeAlias" }, documentTypes);
                  }
                  qry = qry.And().GroupedOr(new[] { "nodeName", "id" }, new string[] { "Network - Marine Conservation" });
                  return qry;
             });
```
Other notes ... You shouldn't need to use GroupedOr for single values like `e.GroupedOr(new string[] { "hideFromSearch" }, "0")` , should just be a `Field` call, also you shouldn't have to `ToList()` an array of fields.

**Comment by mistyn8** [comment]
Thanks for the help, much appreciated.

ps the ToList() was just following the wiki.
https://github.com/Shazwazza/Examine/wiki/Grouped-Operations
