### ISSUE TITLE
SearchResults.Values empty in debugger

### ISSUE THREAD

**Issue by gunnim** [Shazwazza/Examine#130]
If you enumerate the Values property of an ISearchResult while debugging in visual studio it will have a Value of null permanently.

This is probably an issue with the debugger or dotnet but I can't be arsed to pinpoint what exactly in your code causes the issue so as to file a bug with them. Rather than completely ignoring the problem I'd rather you knew about it.

Feel free to close this.

**Comment by Shazwazza** [comment]
The debugger will have problems when things lazily execute, it knows about a lot of lazy execution but prob not all scenarios. Not really an Examine issue, something more in the guts of VS.
