### ISSUE TITLE
Everything is internal/private

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#132]
@Shazwazza 
Hi,
Shannon, actually I am reimplementing big part of examine in my package as everything related to Lucene query is internal/private. Is any reason behind that? As I would prefer to not recreate logic implemented already in examine and just inherit that from source but as my package is not part of your project I am not able to use internal/private methods :) Maybe we will find the best way of handling that for Lucene compatible searchers (Elastic / Azure / another)?

**Comment by Shazwazza** [comment]
Things that are internal/private is mostly like because there are APIs in there that i don't want to expose publicly or maintain as public APIs, or i know are volatile and their signatures might change. 

Happy to review certain APIs to make them public but you have to tell me which ones you are wanting.

**Comment by bielu** [comment]
@Shazwazza actually I change a lot in my code and not able anymore to just inherit from internal methods as I have to escape for few cases here as Elastic handle little different queries and special characters have to be escaped, but when I was writing that question I was using not changed:
`  protected internal LuceneBooleanOperationBase FieldInternal(string fieldName, IExamineValue fieldValue, Occur occurrence)
        {
            if (fieldName == null) throw new ArgumentNullException(nameof(fieldName));
            if (fieldValue == null) throw new ArgumentNullException(nameof(fieldValue));
            return FieldInternal(fieldName, fieldValue, occurrence, true);
        }

        private LuceneBooleanOperationBase FieldInternal(string fieldName, IExamineValue fieldValue, Occur occurrence, bool useQueryParser)
        {
            Query queryToAdd = GetFieldInternalQuery(fieldName, fieldValue, useQueryParser);

            if (queryToAdd != null)
                Query.Add(queryToAdd, occurrence);

            return CreateOp();
        }

        protected internal LuceneBooleanOperationBase GroupedAndInternal(string[] fields, IExamineValue[] fieldVals, Occur occurrence)
        {
            if (fields == null) throw new ArgumentNullException(nameof(fields));
            if (fieldVals == null) throw new ArgumentNullException(nameof(fieldVals));

            //if there's only 1 query text we want to build up a string like this:
            //(+field1:query +field2:query +field3:query)
            //but Lucene will bork if you provide an array of length 1 (which is != to the field length)

            Query.Add(GetMultiFieldQuery(fields, fieldVals, Occur.MUST), occurrence);

            return CreateOp();
        }

        protected internal LuceneBooleanOperationBase GroupedNotInternal(string[] fields, IExamineValue[] fieldVals)
        {
            if (fields == null) throw new ArgumentNullException(nameof(fields));
            if (fieldVals == null) throw new ArgumentNullException(nameof(fieldVals));

            //if there's only 1 query text we want to build up a string like this:
            //(!field1:query !field2:query !field3:query)
            //but Lucene will bork if you provide an array of length 1 (which is != to the field length)

            Query.Add(GetMultiFieldQuery(fields, fieldVals, Occur.MUST_NOT, true),
                //NOTE: This is important because we cannot prefix a + to a group of NOT's, that doesn't work. 
                // for example, it cannot be:  +(-id:1 -id:2 -id:3)
                // it just needs to be          (-id:1 -id:2 -id:3)
                Occur.SHOULD);

            return CreateOp();
        }

        protected internal LuceneBooleanOperationBase GroupedOrInternal(string[] fields, IExamineValue[] fieldVals, Occur occurrence)
        {
            if (fields == null) throw new ArgumentNullException(nameof(fields));
            if (fieldVals == null) throw new ArgumentNullException(nameof(fieldVals));

            //if there's only 1 query text we want to build up a string like this:
            //(field1:query field2:query field3:query)
            //but Lucene will bork if you provide an array of length 1 (which is != to the field length)

            Query.Add(GetMultiFieldQuery(fields, fieldVals, Occur.SHOULD, true), occurrence);

            return CreateOp();
        }
        
        protected internal LuceneBooleanOperationBase IdInternal(string id, Occur occurrence)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));

            //use a query parser (which uses the analyzer) to build up the field query which we want
            Query.Add(_queryParser.GetFieldQueryInternal(LuceneIndex.ItemIdFieldName, id), occurrence);

            return CreateOp();
        }`

**Comment by Shazwazza** [comment]
You can work around some of the internals in Examine since many are also protected so you can inherit from the base class and expose the protected method yourself.

**Comment by Shazwazza** [comment]
(Closing this since it's just a question)
