### ISSUE TITLE
Range Query error on Date Time 

### ISSUE THREAD

**Issue by MosabAbuzaid** [Shazwazza/Examine#139]
Hi 
I want to write an examine search that return files between tow dates come from property value so i tried to use range query and here is my code :
`var searcher = indx.GetSearcher();
                    ISearchResults results = null;
                    results = searcher.CreateQuery()
                    .Field("path", Umbraco.Media(124111).Path.MultipleCharacterWildcard()).And()
                    .Field("__NodeTypeAlias", "File").And()
                    .RangeQuery<DateTime>("fileDate".Split(','),Convert.ToDateTime("04/06/2017"),DateTime.Now)
                    .Execute();
but i faced this error :

![image](https://user-images.githubusercontent.com/38281155/67380245-b4459480-f592-11e9-928e-d38755abdc7f.png)
`

**Comment by Shazwazza** [comment]
Yes, the issue occurs because the field you are searching on `fileDate` is not configued to be a date time value type. 

Some docs are here on how to configure value types for certain fields: https://shazwazza.github.io/Examine/configuration
