### ISSUE TITLE
CreateQuery does nothing with the supplied category

### ISSUE THREAD

**Issue by ronaldbarendse** [Shazwazza/Examine#143]
According to the [Umbraco documentation](https://our.umbraco.com/documentation/reference/searching/examine/examine-events), using `searcher.CreateQuery("content")` should only return content, but it currently doesn't do anything with the category and will thus also return media.

I don't expect the following should be required to get it to correctly filter on the category/index type:

```c#
var luceneQuery = (LuceneSearchQuery)searcher.CreateQuery(IndexTypes.Content);
var searchResults = luceneQuery.Field(LuceneIndex.CategoryFieldName, luceneQuery.Category).And().ManagedQuery("test").Execute();
```

If this bug is fixed and a new Examine version is released, it should be made the minimum required dependency version for Umbraco, so the following bugfix will also work as expected: https://github.com/umbraco/Umbraco-CMS/pull/7038.

**Comment by Shazwazza** [comment]
Wow that's quite an oversight! 🤦‍♂️I'll fix this up right away.

**Comment by Shazwazza** [comment]
Fixed in c6fb9b6d3a563e132fda4182c0b0b83bb697de98

**Comment by Shazwazza** [comment]
The test is here https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1664

**Comment by Shazwazza** [comment]
New version is published https://github.com/Shazwazza/Examine/releases/tag/v1.0.2
