### ISSUE TITLE
Search on field level doesn't work

### ISSUE THREAD

**Issue by bjarnef** [Shazwazza/Examine#145]
Not sure if it is a know bug, but it seems search on field `level` doesn't work?

```
Umbraco v7.15.3
Examine v0.1.89
```

```
var searcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
var criteria = searcher.CreateSearchCriteria();
var query = criteria.NodeTypeAlias("brand")
                               .And()
                               .Field("level", "3")
                               .And()
                               .GroupedOr(new[] { "nodeName", "urlName", "searchKeywords" }.ToList(), new[] { term.MultipleCharacterWildcard() })
                               .Compile();
```
Lucene query:
`+__NodeTypeAlias:brand +level:3 +(nodeName:cold* urlName:cold* searchKeywords:cold*)`

I also tried with `GroupedOr` but seems it also doesn't return the expected result, which is similar to the examples here: https://github.com/Shazwazza/Examine/wiki/Grouped-Operations#groupedor

```
var searcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
var criteria = searcher.CreateSearchCriteria();
var query = criteria.NodeTypeAlias("brand")
                               .And()
                               .GroupedOr(new[] { "level" }.ToList(), new[] { "3" })
                               .And()
                               .GroupedOr(new[] { "nodeName", "urlName", "searchKeywords" }.ToList(), new[] { term.MultipleCharacterWildcard() })
                               .Compile();
```

Lucene query:
`+__NodeTypeAlias:brand +(level:3) +(nodeName:cold* urlName:cold* searchKeywords:cold*)`

A workaround for now seems to be using `Range` method in this case, which only return `brand` nodes on level 3.

```
var searcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
            var criteria = searcher.CreateSearchCriteria();
            var query = criteria.NodeTypeAlias("brand")
                                           .And()
                                           .Range("level", 3, 3)
                                           .And()
                                           .GroupedOr(new[] { "nodeName", "urlName", "searchKeywords" }.ToList(), new[] { term.MultipleCharacterWildcard() })
                                           .Compile();
```

Lucene query:
`+__NodeTypeAlias:brand +level:[3 TO 3] +(nodeName:cold* urlName:cold* searchKeywords:cold*)`

Maybe it is because `level` is a numeric field.

**Comment by Shazwazza** [comment]
Yes level is a numeric field, you can check that is the case with Luke. You can try doing

`.Field("level", 3)` instead of `.Field("level", "3")`

**Comment by bjarnef** [comment]
@Shazwazza the `Field` method only accept string as the second parameter and `GroupedOr` also accept a string array, but not int array.

Maybe it has changed in a newer version og Examine?

**Comment by Shazwazza** [comment]
ah, you are using an old version. Sorry then yes you must use a range query for numerical fields.

**Comment by bjarnef** [comment]
@Shazwazza Okay, when was the overload of `Field` method accepting int as parameter introduced? It is possible to update the Examine version in Umbraco v7 or is it as feature in Examine v1 for Umbraco v8?

**Comment by Shazwazza** [comment]
It's purely an Examine 1.x API 
Current examine versions won't get new functionality and the APIs can't easily be changed without introducing breaking changes.

**Comment by Shazwazza** [comment]
Id isn't stored as a numerical value, though i think parentId is in umbraco v8. Just because it is numerical doesn't mean it's stored that way, it depends on how the index is configured.
