### ISSUE TITLE
publishing node waste the order

### ISSUE THREAD

**Issue by MosabAbuzaid** [Shazwazza/Examine#150]
Hi Shanon 

i am using the sortable field to sort my results on create date like the bellow 

`ExamineResults=QueryOperation.OrderBy(new SortableField ("createDate")).Excecute();`

and its working but when i save and publish an existing node it will be come like the first result 
like as i created it why that is happens and how can i solve that ?

**Comment by MosabAbuzaid** [comment]
Hi Shanon 
help me please

**Comment by Shazwazza** [comment]
what value is being put in the index for `createDate` sounds like the value being put in there is actually the 'update' date.

I will close this issue since it's more of a question, if this is related to Umbraco please try using the Umbraco forum https://our.umbraco.com/
