### ISSUE TITLE
TooManyClauses error in Umbraco search

### ISSUE THREAD

**Issue by RyanDansie** [Shazwazza/Examine#154]
I have an Umbraco website, which uses Examine for its website search functionality. A user found an issue where the site throws an error if too many search words were used in the search term. The error is:
Lucene.Net.Search.BooleanQuery+TooManyClauses: maxClauseCount is set to 1024

In this particular case, the word "test" repeated 5 times in enough to cause the error. We have checked a few other websites and suspect that this issue would actually affect most Umbraco websites, with variations on the length of search term needed to break it. We tested a couple more and kept adding words to the search term until it broke.

I don't know but suspect its related to the number of different text fields on the umbraco site, and the trigget point for this error wouldbe something like: [number of words in search term * number of text fields on site > 1024].

I am currently just looking for how to increase the maxClauseCount property and am unable to find anything about it in the umbraco documentation. I also checked the "configuration" section of the Examine documentation and there isn't any reference to that property there either:
https://shazwazza.github.io/Examine/configuration

If anyone could point me in the right direction for how to increase the maxClauseCount I would be very grateful.

Thanks,

Ryan

**Comment by Chris-N1** [comment]
We had a similar problem and I solved it with some code in an Application start up handler along with a setting in the web.config (we have an extremely large site to deal with and there are a lot of fields):
<add key="LuceneMaxClauses" value="8192" />
`protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            base.ApplicationStarted(umbracoApplication, applicationContext);
            try
            {
                //up the max clause limit for Lucene because the site is too big - settable in the web.config
                var newLimit = ConfigurationManager.AppSettings["LuceneMaxClauses"].ToString();
                int intNewLimit = -1;
                if (int.TryParse(newLimit, out intNewLimit) && intNewLimit > 0)
                {
                    BooleanQuery.SetMaxClauseCount(intNewLimit);
                }
                else
                {
                    BooleanQuery.SetMaxClauseCount(8192);
                }
            }
            catch(Exception ex)
            {
                BooleanQuery.SetMaxClauseCount(8192);
                LogHelper.Error(typeof(ExamineIndexer),"Failed to find config setting for Lucene Max Clauses or set the value - using default", ex);
            }`

**Comment by Shazwazza** [comment]
This will generally happen if you use the generic search on a single term which will then search over ALL fields in your index which causes this problem. The work around above is one solution but another is to ensure you are only searching on fields that you want to search on.
