### ISSUE TITLE
Make Examine not only Web package

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#157]
Examine is making things easier when you won't use lucene.net, and I think we shouldn't limit the usage of Examine to the solutions which are the only web-based. I think it could be great to use Examine in a console app or microservice :)

**Comment by Shazwazza** [comment]
yep sure, so basically removing any dependencies on System.Web you mean? for vNext with aspnet core of course we should do this but would you want to do this today with the current net framework version?

**Comment by bielu** [comment]
@Shazwazza Yes, this is what I mean, but actually I don't think so we should introduce that in the current version, as it will be breaking change. We could introduce that in vNext even in .net implementation.

**Comment by cloudb0x** [comment]
Has this been addressed? Currently getting 

`Could not load type 'System.Web.Hosting.IRegisteredObject' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

**Comment by Shazwazza** [comment]
@cloudb0x Yes, this is tagged for milestone 2.0.0. It will not be addressed for prior versions.
