### ISSUE TITLE
Problem with GroupedNot

### ISSUE THREAD

**Issue by pbres** [Shazwazza/Examine#16]
When using GroupedNot  method with one field and multiple values only first value is added to query:

E.g.
searchCriteria.NodeTypeAlias("myDocumentTypeAlias");
searchCriteria.GroupedNot(new[] { "id" }.ToList(), new [] {"1","2","3"});

output query:
LuceneQuery: {+__NodeTypeAlias:myDocumentTypeAlias +(-id:1)}

Also, produced query is not working because of additional + sign right before opening bracket.
Correct query should looks like this:

+__NodeTypeAlias:myDocumentTypeAlias -id:(1 2 3) 
or 
+__NodeTypeAlias:myDocumentTypeAlias -id:1 -id:2 -id:3 
or 
+__NodeTypeAlias:myDocumentTypeAlias -(id:1 id:2 id:3)

**Comment by Shazwazza** [comment]
Have fixed and added unit tests for this. I'll update the docs for the fluent API output of the "Grouped" methods since And, Or and Not all behave slightly differently.

**Comment by Shazwazza** [comment]
https://github.com/Shazwazza/Examine/wiki/Grouped-Operations
