### ISSUE TITLE
Periodically close and reopen an IndexWriter to avoid memory leaks

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#179]
This is a known issue in Lucene that keeping an IndexWriter open forever with a ton of writes will eventually cause memory to leak/grow.

We need to periodically close and reopen an IndexWriter. RavenDb does this by tracking number of writes and when it reaches a threshold it closes and reopens. We can probably do something similar. See comment https://github.com/Shazwazza/Examine/pull/174#issuecomment-678013901

**Comment by nzdev** [comment]
Might need to track the reads as well.

**Comment by berendhaan** [comment]
@Shazwazza Do you have a link to the source of RavenDb where they implement this?

We are running to some memory issues using AzureDirectory and writing a lot of times to the index while keeping the writer open for the lifetime of the application.

**Comment by Shazwazza** [comment]
@berendhaan are you running a fork of AzureDirectory or is this for Examine 0.1.x? Are you sure this memory issue is because of this? Sorry I don't have the link to ravendb source. I haven't seen any specific examples of this issue in real life.

**Comment by berendhaan** [comment]
We are using a fork, Lucene.Net.Store.Azure, I guess your implementation is based on this?
I was triggered because we do a lot of writers and keeping the index open.

**Comment by nzdev** [comment]
I believe this can now be closed. With Lucene.NET 4 this is implemented in Examine 3.
