### ISSUE TITLE
Search results: retrieve only specific fields instead of returning the whole doc.

### ISSUE THREAD

**Issue by Alain-es** [Shazwazza/Examine#18]
Hi,

I have been reading the Examine's documentation and looking for in Umbraco forums, but couldn't find anything.
I was wondering if it is possible to retrieve only specific fields instead of returning the whole doc in the search results?
If not so, would it be difficult to implement this feature (I am considering to submit a PR)?

I have found the following doc/examples on the internet:
http://lucene.apache.org/core/2_9_4/api/all/org/apache/lucene/document/FieldSelector.html
http://lucene.apache.org/core/2_9_4/api/all/org/apache/lucene/document/FieldSelectorResult.html
http://kb.ucla.edu/articles/why-are-lucenes-stored-fields-so-slow-to-access
Would it be the correct way to implement this feature?

Thanks,
Alain

**Comment by Shazwazza** [comment]
Would be a good feature to implement, would need to look at adding a field filter or something to the search criteria that gets passed in and then using the underlying lucene api's to filter.

**Comment by Alain-es** [comment]
Please let me know whether I can help or do it myself by submitting a PR.
Thanks

**Comment by Shazwazza** [comment]
Has been done in this PR https://github.com/Shazwazza/Examine/pull/173
