### ISSUE TITLE
OutOfMemoryException while reindexing

### ISSUE THREAD

**Issue by nzdev** [Shazwazza/Examine#186]
OutOfMemoryException while reindexing a large amount of documents. The BlockingCollection in LuceneIndexer needs to have the boundedCapacity set to stop the producer filling the blocking collection and running out of memory before the documents are read from the collection and written to lucene.

**Comment by Shazwazza** [comment]
Nice catch, do you have any opinions on what this size should be?

**Comment by nzdev** [comment]
Not sure. I think it should be configurable so people can choose what works for them as it trades for speed.

**Comment by nzdev** [comment]
Observed on v0.9.1.0

**Comment by nzdev** [comment]
Index should be commited more often than 5 mins as well (i think) so the problem is solved on both sides.

**Comment by Shazwazza** [comment]
I'll think about what the default should be. The index is committed as soon as it can once ScheduleCommit is called but if ScheduleCommit keeps being called then the maximum wait time period is 5 minutes. That will only occur for huge writing operations that take that amount of time.

**Comment by Shazwazza** [comment]
Fixed in rev: 252c4c04f7e803054d08cf74c4be4bf28909a2bb

Default limit is 1000, this can be set via a parameter in the ctor. However for Umbraco based Lucene indexes this would require that new ctors are created there too so I've made the static DefaultQueueCapacity read/write so you can modify the default at the very beginning of the app before the default ctors are used.

**Comment by nzdev** [comment]
Any chance of getting this fixed in 0.20 as well @Shazwazza

**Comment by Shazwazza** [comment]
@nzdev yep should be fine and good point. Is there a way you can test out these limits before anything is released? Would you need a build of 0.2 to test?

**Comment by nzdev** [comment]
A nuget package would help, however I think the umbraco indexer gets 1000+ items per IEnumerable, so that's 1000*1000 in the queue.

**Comment by nzdev** [comment]
Unfortunately this does not appear to have been fixed by the change

**Comment by Shazwazza** [comment]
Were you able to try tweaking the LuceneIndex.DefaultQueueCapacity on startup before any examine things take place to see if there's a more appropriate number?

But yeah I can see this is a challenge since the queue is really a queue of a collection.
