### ISSUE TITLE
GroupedFlexible is no more?

### ISSUE THREAD

**Issue by TheBekker** [Shazwazza/Examine#189]
In older versions Examine there was an IBooleanOperation called "GroupedFlexible", but that doesn't seem to exist anymore?
It's was very usefull and well, very flexible :)

Is GroupedFlexible gone for good?

**Comment by Shazwazza** [comment]
There is no plans to bring back GroupedFlexible, instead 1.0.0 comes with a more flexible way to nested queries. The docs are in need of updating https://shazwazza.github.io/Examine/searching.html ... and would love for anyone to help contribute to them https://github.com/Shazwazza/Examine/issues/190  :) 

Here's an example of nested queries which you couldn't do before https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1735 so now you can have any level of nested queries.

**Comment by TheBekker** [comment]
Ahh very cool, i'll look in to that.
Maybe even contribute to the docs when i'd had a go at using it :)
