### ISSUE TITLE
Raw lucene sub-query

### ISSUE THREAD

**Issue by Alain-es** [Shazwazza/Examine#19]
I was wondering whether there is way to add raw lucene sub-queries.

If not so, would be very difficult to implement a method like RawQuery(string rawQuery)? That would help to create complex queries using the Fluent API.

Example:
```
var query = searchCriteria
	.Fields("nodeName","hello")
	.And().RawQuery(" +(metaTitle:hello metaDescription:goodbye)")
	.Compile();
```

**Comment by Shazwazza** [comment]
No that is not possible. If you want to write a raw query then you should just write the entire thing as a raw query.

**Comment by Shazwazza** [comment]
... it is possible but it is a breaking change and would require anything that implements the interface to deal with random, custom strings inside query creation which will ultimately just lead to problems and would be difficult to debug.

**Comment by Alain-es** [comment]
You are right, it can be quite difficult to debug.
Thank you.
