### ISSUE TITLE
Docs need updates - searching page

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#190]
There's plenty of places in the searching page that have TODOs listed https://shazwazza.github.io/Examine/searching.html would love for anyone to help update these. There's plenty of examples in the fluent api unit tests in the repo.

The docs are built with GitHub pages and Jekyll and the files are just markdown found here https://github.com/Shazwazza/Examine/tree/master/docs

**Comment by bjarnef** [comment]
I noticed in Umbraco v9 using Examine v2 it seems `IIndex` no longer has a `GetSearcher()` method, but instead it is `Searcher` property.

**Comment by nzdev** [comment]
I think this can be closed as done.
