### ISSUE TITLE
Docs need updates - sorting

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#192]
The sorting page is pretty much empty and needs to be filled in https://shazwazza.github.io/Examine/sorting.html

Doesn't need to be done all at once, any help here is greatly appreciated!

The docs are built with GitHub pages and Jekyll and the files are just markdown found here https://github.com/Shazwazza/Examine/tree/master/docs

**Comment by nzdev** [comment]
I think this can be closed as done.
