### ISSUE TITLE
Order by exact field value

### ISSUE THREAD

**Issue by deekoulos** [Shazwazza/Examine#194]
Hi there!

I am wondering if there is a way to order boolean operations by exact field values.

For instance, there is an integer field named membership status. entries could have a value in this field or their value is null. I need an ordering by the exact value field of 1234. So all entries, which have exactly the value 1234 for this field should be on top.

current ordering for other fields is done like this:

`        sortedBooleanOperation = booleanOperation.OrderByDescending(new SortableField("memberGroups", SortType.String));`

I would appreciate any useful ideas. Currently this is blocking one of the important components of the business model.

Thanks
Dee

**Comment by Shazwazza** [comment]
That's not something I've heard of doing or have any experience in trying to do. Your best bet is to look into if it's possible to do this with Lucene (and Lucene.Net). Once that can be determined then it could be figured out how to get that logic into the Examine results using the lucene objects available.
