### ISSUE TITLE
Indexing Issues with AzureDirectory

### ISSUE THREAD

**Issue by 0Neji** [Shazwazza/Examine#206]
Hi,

We're currently trying (and failing!) to migrate a large Umbraco site to Azure from a traditional server. One of the issues we run into early on was with indexing and getting errors with them being locked. We also use autoscaling which means that indexes need to rebuild when a new instance is spun up. So moving those indexes to blob storage seemed to be the perfect solution.

We've ran through config as outlined at: https://shazwazza.com/post/examine-and-azure-blob-storage/

This has worked okay, we've had the site up and running, indexes built to blob storage. However, during testing we were editing content whilst users were visiting the site. Around this time, we saw the site go down, server a 500 error. It looks like the indexes are getting corrupt for reasons unknown. When this happens, we get the following error in the dashboard:

![image](https://user-images.githubusercontent.com/4700480/105228345-62efd080-5b5a-11eb-8022-055a882c689f.png)

When we get the errors, they sometimes fix themselves (indexing retries?) and sometimes they don't but the site does come up immediately after rebuilding the index).

I've also attached a log file which shows some of the errors, a couple of the choice ones being:

```
ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=InternalIndexer, NodeId=-1
System.Exception: An error occurred during the index commit operation, if this error is persistent then index rebuilding is necessary,System.IO.IOException: Cannot overwrite: C:\local\Temp\ExamineIndexes\43838afbd3adce668673edfda6d31300\Internal\_3sr.cfs
```

```
ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=ExternalIndexer, NodeId=-1
System.Exception: An error occurred during the index commit operation, if this error is persistent then index rebuilding is necessary,System.IO.FileNotFoundException: _2km_wi.del ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
```

A few more bits of info which may (or may not) help:

1. Umbraco 7.15.6
2. Examine 0.1.92
3. Examine.AzureDirectory 0.1.90
4. Azure is setup with two app service plans, one for the CMS, one for the FE. The CMS server does not auto-scale. The FE has auto-scale set up so created instances on the fly as and when needed.
5.  Our media files are served through the same blob storage container

Hopefully plenty of info to get stuck in, but please let me know if you need any more details.

Thanks,

Ben

**Comment by Shazwazza** [comment]
Hi, there are known issues with Azure Directory and some community folks are helping out with this. 

The discussion is in several places, but you can start here https://github.com/Shazwazza/Examine/issues/160#issuecomment-681903262 ... which leads to a PR https://github.com/Shazwazza/Examine/pull/193 which leads to other PRs for the latest versoin.

Various things need to be changed and handled to make it work correctly so that lucene merges aren't getting in the way.

**Comment by 0Neji** [comment]
Thanks for getting back to me so quickly @Shazwazza - we'll test an alternate route for now. I'll close this one as I've subscribed to the other discussions and will keep an eye on them.
