### ISSUE TITLE
Enable adding/indexing of documents with duplicate fields (array fields)

### ISSUE THREAD

**Issue by xumix** [Shazwazza/Examine#21]
What I need is ability to index documents with multi-value fields, eg. tags. There is no way I can add a document with many values for the same field

**Comment by Shazwazza** [comment]
This functionality already exists, see: https://github.com/Shazwazza/Examine/issues/6

**Comment by Shazwazza** [comment]
You need to use the DocumentWriting event to modify the lucene doc directly to achieve this currently. In v2 this is possible with the normal APIs but it's an api breaking to accomplish this in v1.

See the unit test: https://github.com/Shazwazza/Examine/blob/master/Projects/Examine.Test/Index/IndexTest.cs#L58
