### ISSUE TITLE
Sorting by name doesn't work as expected

### ISSUE THREAD

**Issue by bjarnef** [Shazwazza/Examine#228]
Based on Umbraco v8.13.0 and Examine v1.1.0 I am fetching some exployee node and sorting these by node name.

```
var results = query.OrderBy(new SortableField("name", SortType.String)).Execute(pageSize * page);
var totalResults = results.TotalItemCount;
var pagedResults = results.Skip(pageSize * (page - 1));

var items = pagedResults.ToPublishedSearchResults(_umbracoContextAccessor.UmbracoContext.Content)
         .Select(x => x.Content)
         .OfType<Employee>();

return new PagedResult<Employee>(totalResults, page, pageSize)
{
        Items = items
};
```

It is pretty much similar to this example from Vendr demo store:
https://github.com/vendrhub/vendr-demo-store/blob/main/src/Vendr.DemoStore/Web/Controllers/ProductSurfaceController.cs#L66-L68

On the first page the employees are sorted alphabetically, but on last page I then get employees with e.g. "A" and "L", where the previous page 3 has employeees with "S".

In seems these employees are some of the last employees created.
Not sure if this is a bug in Examine or something in Umbraco core?

I saw some older posts for Umbraco v7 using `nodeName` instead of `name`, but this doesn't seem to work in v8, while `name` works (except on last page in this case).
https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/96251-problems-sorting-examine-search-results

Not sure why `new SortableField("nodeName", SortType.String)` doesn't seem to order the results by node name as the index does contain this property.

**Comment by bjarnef** [comment]
I tried adding the following:

```
public class ExamineComponent : IComponent
{
    private readonly IExamineManager _examineManager;
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public ExamineComponent(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory)
    {
        _examineManager = examineManager;
        _umbracoContextFactory = umbracoContextFactory;
    }

    public void Initialize()
    {
        ConfigureExamine();
    }

    public void Terminate()
    {
        
    }

    protected void ConfigureExamine()
    {
        // Listen for nodes being reindexed in the external index set
        if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var index))
        {
            ((BaseIndexProvider)index).TransformingIndexValues += (object sender, IndexingItemEventArgs e) =>
            {
                index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("nodeName", FieldDefinitionTypes.FullTextSortable));
                
                // Create searchable path
                if (e.ValueSet.Values.ContainsKey("path"))
                {
                    e.ValueSet.Add("searchPath", e.ValueSet.GetValue("path").ToString().Replace(',', ' '));
                }

                // Stuff all the fields into a single field for easier searching
                var combinedFields = new StringBuilder();

                foreach (var kvp in e.ValueSet.Values)
                {
                    foreach (var value in kvp.Value)
                    {
                        combinedFields.AppendLine(value.ToString());
                    }
                }

                e.ValueSet.Add("contents", combinedFields.ToString());
            };
        }
    }
}
```

and updated the search:

```
var results = query.OrderBy(new SortableField("nodeName", SortType.String)).Execute(pageSize * page);
var totalResults = results.TotalItemCount;
var pagedResults = results.Skip(pageSize * (page - 1));

var items = pagedResults.ToPublishedSearchResults(_umbracoContextAccessor.UmbracoContext.Content)
        .Select(x => x.Content)
        .OfType<Employee>();

return new PagedResult<Employee>(totalResults, page, pageSize)
{
       Items = items
};
```

but it didn't really seem to work - at least not in alphabetically order :)

**Comment by bjarnef** [comment]
Okay, I actually had some additional 


```
try
{
   using (var ctx = _umbracoContextFactory.EnsureUmbracoContext())
   {
       ...
   }
}
catch (Exception ex)
{
      throw;
}
```

The employees nodes was indexes and returned in frontend.

When removing this try/catch block and re-indexing again, it works fine using `nodeName` with the changes in https://github.com/Shazwazza/Examine/issues/228#issuecomment-842164329

`name` also work (almost), but on last page I got some employees starting with "A" in name.

**Comment by bjarnef** [comment]
Hmm strange... after re-indexing sorting on `nodeName` didn't work and a different sorting each time re-indexing.

**Comment by bjarnef** [comment]
@Shazwazza sorting the nodes alfabetically and use `new SortableField("sortOrder", SortType.Int)` instead works.

You have created this issue https://github.com/Shazwazza/Examine/issues/192 regarding updating the documentation, which mention examples here: https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs

It has examples using `new SortableField("nodeName", SortType.String)` so I wonder why it doesn't work on this project.

It seems it isn't documented that `name` can be used as well:
https://github.com/vendrhub/vendr-demo-store/blob/a976c4eafefcd3e92acbc9d65d4c73b529746e36/src/Vendr.DemoStore/Web/Controllers/ProductSurfaceController.cs#L66

**Comment by Shazwazza** [comment]
> It has examples using new SortableField("nodeName", SortType.String) so I wonder why it doesn't work on this project.

What is the field type you are using for this?

> sorting the nodes alfabetically and use new SortableField("sortOrder", SortType.Int) instead works.

Yes, sortOrder is probably a numerical type and this is just going to sort on the sortOrder field, nothing to do with your name

> It seems it isn't documented that name can be used as well:

Not sure what you mean here. You can sort on any field so long as it's sortable. If 'name' is a field, you can sort on it. 

Here's an example of sorting on a text field: https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1011

The field type needs to be sortable: 
https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1017

These are the built in types https://shazwazza.github.io/Examine/configuration.html#default-value-types

**Comment by Shazwazza** [comment]
Umbraco doesn't do anything special for 'nodeName' so by default its just a FullText field. These are the default umbraco field definitions for indexes https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Examine/UmbracoFieldDefinitionCollection.cs#L24

I'll close this now since making this into FullTextSortable will work

**Comment by Shazwazza** [comment]
I updated some of the docs https://shazwazza.github.io/Examine/sorting.html

**Comment by bjarnef** [comment]
@Shazwazza okay, I guess `sortOrder` is by default sortable or because it is indexes as a numerical type.

`nodeName` is the name of the Umbraco node, but not sure what `name` field is? It isn't shown in Examine dashboard.
In Vendr this is products based on Umbraco nodes:
https://github.com/vendrhub/vendr-demo-store/blob/main/src/Vendr.DemoStore/Web/Controllers/ProductSurfaceController.cs#L66

As in the example here https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L1011 I tried with `index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("nodeName", FieldDefinitionTypes.FullTextSortable));` which marked the field as sortable, but the results wasn't sorted alphabetically.

In fact each time I re-indexed it seems to change the sorting of the results.

**ExamineComponent.cs**

```
public class ExamineComponent : IComponent
{
    private readonly IExamineManager _examineManager;
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public ExamineComponent(IExamineManager examineManager, IUmbracoContextFactory umbracoContextFactory)
    {
        _examineManager = examineManager;
        _umbracoContextFactory = umbracoContextFactory;
    }

    public void Initialize()
    {
        ConfigureExamine();
    }

    public void Terminate()
    {
        
    }

    protected void ConfigureExamine()
    {
        // Listen for nodes being reindexed in the external index set
        if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var index))
        {
            ((BaseIndexProvider)index).TransformingIndexValues += (object sender, IndexingItemEventArgs e) =>
            {
                index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("nodeName", FieldDefinitionTypes.FullTextSortable));

                // ================================================================
                // Do some generally usefull modifications
                // ================================================================

                // Create searchable path
                if (e.ValueSet.Values.ContainsKey("path"))
                {
                    e.ValueSet.Add("searchPath", e.ValueSet.GetValue("path").ToString().Replace(',', ' '));
                }

                // Stuff all the fields into a single field for easier searching
                var combinedFields = new StringBuilder();

                foreach (var kvp in e.ValueSet.Values)
                {
                    foreach (var value in kvp.Value)
                    {
                        combinedFields.AppendLine(value.ToString());
                    }
                }

                e.ValueSet.Add("contents", combinedFields.ToString());
            };
        }
    }
}
```

**EmployeeSurfaceController.cs**

```
public class EmployeeSurfaceController : SurfaceController
{
    private readonly IExamineManager _examineManager;
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public EmployeeSurfaceController(IExamineManager examineManager, IUmbracoContextAccessor umbracoContextAccessor)
    {
        _examineManager = examineManager;
        _umbracoContextAccessor = umbracoContextAccessor;
    }

    [ChildActionOnly]
    public ActionResult Search(string q = "", int[] departmentIds = null, int[] categoryIds = null, int p = 1, int ps = 12)
    {
        return PartialView("PagedEmployeeList", GetPagedEmployees(q, departmentIds, categoryIds, p, ps));
    }

    [ChildActionOnly]
    public ActionResult EmployeeListByDepartment(int departmentId, string q = "",  int p = 1, int ps = 12)
    {
        return PartialView("PagedEmployeeList", GetPagedEmployees(q, new int[] { departmentId }, null, p, ps));
    }

    private PagedResult<Employee> GetPagedEmployees(string term, int[] departmentIds, int[] categoryIds, int page, int pageSize)
    {
        if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var index))
        {
            var searcher = index.GetSearcher();
            var query = searcher.CreateQuery().NodeTypeAlias(Employee.ModelTypeAlias);

            var searchFields = new[] { "nodeName", "sections" };

            if (!string.IsNullOrEmpty(term))
            {
                var searchTerms = Tokenize(term);
                query.And().GroupedOr(searchFields, searchTerms.Select(x => x.MultipleCharacterWildcard()).ToArray());
            }

            // Departments
            departmentIds = departmentIds ?? Enumerable.Empty<int>().ToArray();
            
            if (departmentIds.Length > 0)
            {
                query.And().GroupedOr(new[] { "departmentIds" }, departmentIds.Select(x => x.ToString()).ToArray());
            }

            // Categories
            categoryIds = categoryIds ?? Enumerable.Empty<int>().ToArray();

            if (categoryIds.Length > 0)
            {
                query.And().GroupedOr(new[] { "categoryIds" }, categoryIds.Select(x => x.ToString()).ToArray());
            }

            var results = query.OrderBy(new SortableField("nodeName", SortType.String)).Execute(pageSize * page);
            var totalResults = results.TotalItemCount;
            var pagedResults = results.Skip(pageSize * (page - 1));

            var items = pagedResults.ToPublishedSearchResults(_umbracoContextAccessor.UmbracoContext.Content)
                .Select(x => x.Content)
                .OfType<Employee>();

            return new PagedResult<Employee>(totalResults, page, pageSize)
            {
                Items = items
            };
        }

        return new PagedResult<Employee>(0, page, pageSize);
    }

    public IEnumerable<string> Tokenize(string input)
    {
        return Regex.Matches(input, @"[\""].+?[\""]|[^ ]+")
            .Cast<Match>()
            .Select(m => m.Value.Trim('\"').ToLower())
            .ToList();
    }
}
```

**Comment by bjarnef** [comment]
@Shazwazza okay, I just made this change instead:

```
index.FieldDefinitionCollection.TryAdd(new FieldDefinition("nodeName", FieldDefinitionTypes.FullTextSortable));
```

Is this expected? If I use `AddOrUpdate` the results are not sorted, but they are sorted if indexing using `TryAdd`.

**Comment by bjarnef** [comment]
Okay, after I changed to `TryAdd` I can't really get the old behaviour when changing to `AddOrUpdate` and re-indexing.

**Comment by Shazwazza** [comment]
You can't change the field type after the index has initialized, that needs to be done on startup, see https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/#changing-field-value-types

There is a known issue there with Umbraco though: https://github.com/umbraco/Umbraco-CMS/issues/8893

**Comment by bjarnef** [comment]
Isn't the `(not recommended)` part here misleading if you actual want to sort on node name? https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/#changing-field-value-types

You could of course index the node name in a custom field, but I guess that isn't better.

**Comment by bjarnef** [comment]
@Shazwazza yeah, I noticed that 🙈

Okay, but changing `FullText` to `FullTextSortable` shouldn't affect the existing field? It seems the difference here is that `FullTextSortable` add an additional `__Sort_nodeName` field in the index.

So regarding `nodeName` would it make a difference whether to use `TryAdd` vs `AddOrUpdate`? The field `nodeName` should by default exist.

**Comment by Shazwazza** [comment]
> Okay, but changing FullText to FullTextSortable shouldn't affect the existing field? It seems the difference here is that FullTextSortable add an additional __Sort_nodeName field in the index.

Yes, that's exactly what it does, it adds another backing field that is sortable. So when you sort on that field it will use that backing field. You don't need to know about that field.

> So regarding nodeName would it make a difference whether to use TryAdd vs AddOrUpdate? 

As above - yes it will if something else has defined `nodeName` as an existing field definition. If you did TryAdd and it was already there, then nothing would happen right!

> The field nodeName should by default exist.

The field "definition" in Umbraco does __not__ exist by default, as above, you can see the defaults:  https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Examine/UmbracoFieldDefinitionCollection.cs#L24 but there's nothing saying that another package might have already added that field definition, who knows.
