### ISSUE TITLE
Custom members index not update after new member creation (Umbraco 8.13)

### ISSUE THREAD

**Issue by afabri73** [Shazwazza/Examine#232]
Hi,
I create my custom index for specific members types using your guide (founded in https://shazwazza.github.io/Examine/)
In my project I create a new member after login if not already exist in umbraco.
All function properly, but I realized that my custom index not rebuild after new member creation.

This is my code

`var _NewMember = Services.MemberService.CreateMember(WSInfoPersona.AccountDominio,
                                                                                WSInfoPersona.Email,
                                                                                NomeCompleto,
                                                                                "_myCustomMembersIndex_");
Services.MemberService.Save(_NewMember);

IMember NewMember = Services.MemberService.GetByUsername(_NewMember.Username);

Services.MemberService.AssignRole(NewMember.Id, "_myCustomMemberRole_");

Services.MemberService.SavePassword(NewMember, NewADFSMemberPassword);

NewMember.SetValue("memberSAMAccount", WSInfoPersona.AccountDominio.Trim());

Services.MemberService.Save(NewMember);
`
There is a way to force the rebuild of my custom index after saving member?

I also placed same question in our.umbraco.com but I never received answer (https://our.umbraco.com/forum/using-umbraco-and-getting-started/106001-how-to-schedule-rebuild-of-custom-examine-index).

Thank you in advance
Adriano

**Comment by afabri73** [comment]
A little update...after some tests, I saw that new member Exist in the examin index, because if I try to search him in Examine Management (backoffice), I found him.
So the problem is only in frontend.
I have a page to search colleagues and I don't find any of the new members.
I can find them only after a rebuild of my custom index.

Any idea?

**Comment by afabri73** [comment]
SOLVED

I had to modify my Custom Index Creator as follows.

Now I have my custom index always updated.

Adriano

    using Examine;
    using Lucene.Net.Analysis.Standard;
    using Lucene.Net.Util;
    using System.Collections.Generic;
    using Umbraco.Core.Logging;
    using Umbraco.Core.Services;
    using Umbraco.Examine;
    using Umbraco.Web.Search;

    namespace AF.Examine.Index.Tools.For.UmbracoV8.Creators
    {
        public class AFMembersIndexCreator : UmbracoIndexesCreator
        {
            private readonly IProfilingLogger _profilingLogger;
            private readonly ILocalizationService _languageService;
            private readonly IPublicAccessService _publicAccessService;
            private readonly IMemberService _memberService;
            private readonly IUmbracoIndexConfig _iUmbracoIndexConfig;

            // Since Umbraco 8 has dependency injection out of the box, we can use it to inject
            // the different services that we need.
            public AFMembersIndexCreator(IProfilingLogger profilingLogger, 
                                            ILocalizationService languageService, 
                                            IPublicAccessService publicAccessService, 
                                            IMemberService memberService, 
                                            IUmbracoIndexConfig umbracoIndexConfig) : base(profilingLogger, languageService, publicAccessService, memberService, umbracoIndexConfig)
            {
                _profilingLogger = profilingLogger;
                _languageService = languageService;
                _publicAccessService = publicAccessService;
                _memberService = memberService;
                _iUmbracoIndexConfig = umbracoIndexConfig;
            }

            // Noticed that we return a collection of indexes? Technically you
            // can create multiple indexes in an indexCreator :) You can have a look at
            // UmbracoIndexesCreator.cs in the CMS core and see how the CMS does that.
            public override IEnumerable<IIndex> Create()
            {
                // create my AFMembersIndex definitions
                return new[] { CreateAFMembersIndex() };
            }

            private IIndex CreateAFMembersIndex()
            {
                var AFMembersIndex = new UmbracoMemberIndex(
                                                        "AFMembersIndex",
                                                        new FieldDefinitionCollection(
                                                            new FieldDefinition("memberId", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberNodeName", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberLoginName", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberEmail", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberName", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberSurname", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberIntTel", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberFax", FieldDefinitionTypes.FullText),
                                                            new FieldDefinition("memberCel", FieldDefinitionTypes.FullText)
                                                        ),
                                                        CreateFileSystemLuceneDirectory("AFMembersIndex"),
                                                        new StandardAnalyzer(Version.LUCENE_30),
                                                        ProfilingLogger,
                                                        UmbracoIndexConfig.GetMemberValueSetValidator());

                return AFMembersIndex;
            }
        }
    }

**Comment by Shazwazza** [comment]
Thanks for the update and feedback. Regarding:

```
public override IEnumerable<IIndex> Create()
        {
            // create my AFMembersIndex definitions
            return new[] { CreateAFMembersIndex() };
        }
```

You still need to return the standard Umbraco indexes else Umbraco will break. You are replacing this service entirely so now there will only be your index. [The internal, external and default member index](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Search/UmbracoIndexesCreator.cs#L42) won't exist which are requirements of the CMS.

You need to do this:

```
public override IEnumerable<IIndex> Create()
        {
            var umbracoIndexes = new List<IIndex>(base.Create());
            umbracoIndexes.Add(CreateAFMembersIndex());
            return umbracoIndexes;
        }
```

You typically shouldn't create more indexes than you need as this is extra overhead for no real benefit. Is there a reason why you can't just use the built in members index and customize it's fields?
