### ISSUE TITLE
Could not perform a range query on the field path, it's value type is Our.Umbraco.Extensions.Search.LuceneEngine.ValueTypes.ListValueType

### ISSUE THREAD

**Issue by nathanwoulfe** [Shazwazza/Examine#235]
Hi @Shazwazza, following on from @callumbwhyte's CG21 session, I'm having a look at integrating Search Extensions into our site, and hitting an interesting/odd issue. Trace points to Examine, but it's caused by Search Extensions changing the path field from a comma-delimited string to its own list type.

My query looks like this:
```csharp
ISearchResults newsItems = _searchProviderFactory
  .GetTypedQuery(KnownDocumentAlias.News.NewsItem)
  .And()
  .Path(KnownDocumentId.BlogAggregator)
  .And()
  .Field("featureOnHomepage", "1")
  .OrderByDisplayDate()
  .Execute(3);  
```

There's some abstraction and custom extensions in there to simplify syntax, but all it's asking for 3 `newsItem` results, which must be children of `BlogAggregator` and set to appear on the homepage.

`OrderByDisplayDate` does this:
```csharp
public static IOrdering OrderByDisplayDate(this IBooleanOperation query, SortDirection direction = SortDirection.Descending)
{
  if (direction == SortDirection.Descending)
    return query.OrderByDescending(DisplayDateSortField);
  
  return query.OrderBy(DisplayDateSortField);
}
```

`Path()` is an extension: 
```csharp 
public static IBooleanOperation Path(this IQuery query, int id) => query.Field("path", id);
```

Previously this worked fine when we added a custom searchablePath field (pipe-delimited), and searched that field in `Path()` but when path is modified by installing Search Extensions, it throws:
```
   at Examine.LuceneEngine.Search.LuceneSearchQuery.<>c__DisplayClass13_0`1.<RangeQueryInternal>b__0() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Search\LuceneSearchQuery.cs:line 119
   at Examine.LuceneEngine.Search.LateBoundQuery.get_Wrapped() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Search\LateBoundQuery.cs:line 13
   at Examine.LuceneEngine.Search.LateBoundQuery.ExtractTerms(ISet`1 terms) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Search\LateBoundQuery.cs:line 37
   at Lucene.Net.Search.BooleanQuery.ExtractTerms(ISet`1 terms) in d:\Lucene.Net\FullRepo\trunk\src\core\Search\BooleanQuery.cs:line 504
   at Examine.LuceneEngine.LuceneSearchResults.DoSearch(Query query, IEnumerable`1 sortField, Int32 maxResults, Nullable`1 skip, Nullable`1 take) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\LuceneSearchResults.cs:line 80
   at Examine.LuceneEngine.LuceneSearchResults.GetTotalDocs() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\LuceneSearchResults.cs:line 175
   at Examine.SearchResultsBase.<Skip>d__12.MoveNext() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\SearchResultsBase.cs:line 84
   at Examine.LuceneEngine.LuceneSearchResults.DecrementReaderResult.MoveNext() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\LuceneSearchResults.cs:line 287
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

I'm not sure why this would fail, as the generated query looks to be correct (below). The puzzling part is that removing the sorting clause fixes the error, despite the generate query appearing the same. I'm not sure where else to look to resolve this, any advice would be awesome.

![image](https://user-images.githubusercontent.com/3248070/121825553-7280d900-ccf6-11eb-8739-9e68ad8214ca.png)

**Comment by callumbwhyte** [comment]
Hey @nathanwoulfe,

This is juicy - cheers for the info!

You're absolutely right that there's no obvious reason why Search Extensions would cause this, and the query looks sound, BUT I believe I know the issue... I don't believe this is Examine's fault but actually how Umbraco bootstraps Examine.

@JasonElkin recently investigated a similar issue with Umbraco 8 and the order in which it affects Examine index creation: https://github.com/umbraco/UmbracoDocs/issues/3115

Would I be wrong to suspect you have a component that is modifying the index and setting the field type of your `DisplayDateSortField`? Search Extensions also has a component [here](https://github.com/callumbwhyte/umbraco-search-extensions/blob/dev/src/Our.Umbraco.Extensions.Search/Startup/IndexComposer.cs#L12) to register all of it's field types - if yours runs before mine then it will overwrite yours it seems...

To confirm this is the case take a look into the `FieldDefinitionCollection` on the `IIndex` you fetch to perform the query, and see if the field type for your `DisplayDateSortField` matches what you'd expect...

The composer you use to register this component is likely already decorated with an attribute:

```
[ComposeAfter(typeof(ExamineComposer))]
```

...but this still might not be enough. We've found `InsertAfter` is your friend - either insert your component after Umbraco's `ExamineComponent` or my `IndexComponent`. Alternatively I'd be interested to know if composing after my `IndexComposer` would make any difference?

```
[ComposeAfter(typeof(IndexComposer))]
```

Let me know you get on!

Callum

**Comment by nathanwoulfe** [comment]
Cheers @callumbwhyte, will double check tomorrow - fairly sure I've done the ol' InsertAfter and ComposeAfter, but will confirm and check the returned field definitions. 

It's a strange one in that the error refers to the path field, but removing the sort resolves it... Shrugs.

**Comment by JasonElkin** [comment]
Hey @nathanwoulfe it's reasonably easy to determine if it's the same issue I was having.

In the composer where you modify the field definitions pop a breakpoint in and inspect the index's `FieldValueTypeCollection` (a lazy property). It should show the "require all threads to run" message, which is the correct state.

If the collection has been initialised you will see the values in the collection and find that the field with the error doesn't have the same type in the value and the definition collection.

If that's happening then something's causing examine to init before your component is init'd. In my case it was a cache refresher that was firing after examine was configured (examine is subscribed to cache refreshers as soon as it's composed🧐) but before my component was init'd. Compose/InsertAfter solved the problem in the site I was working on by running my code slightly earlier (<100ms) but I don't think there's a 100% effective way to guard against race conditions here.

**Comment by Shazwazza** [comment]
That particular issue is fixed in the CMS https://github.com/umbraco/Umbraco-CMS/pull/10182 and due in 8.15.0

If you want to work around this issue now and not worry about race conditions, you will need to replace the `UmbracoIndexesCreator` with your own and specify the field types either in the ctor of the `UmbracoContentIndex`, or override the call to the `Create` method, call `base.Create` to get the underlying indexes and modify the field defs there.

**Comment by nathanwoulfe** [comment]
Awesome, thanks @Shazwazza. Means I can leave search refactoring alone for a couple of months 😁

**Comment by JasonElkin** [comment]
Ah, sorry @Shazwazza I missed that fix.
