### ISSUE TITLE
Examine 2.0 - ExamineManager doesnt have public method to add index

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#236]
Hi @Shazwazza, 
is any reason to not allow add index through examine manager? :)
In v1 it was possible:
```
   var examineIndex = new ExamineIndex(name,
                    CreateFileSystemLuceneDirectory(name),
                    fields, analyzer);
               _examineManager.AddIndex(examineIndex);
```
              
in v2 IExamineManager doesnt have AddIndex, so I look into code and ExamineManager has method addIndex, but it is private :)

**Comment by Shazwazza** [comment]
Everything in Examine 2 is done by DI. You cannot dynamically add things to the manager, the manager only knows things resolved from DI. `AddIndex` is just used in the ctor to add resolved indexes from DI to itself. There is no more (unsafe) runtime configuration in Examine.

**Comment by Shazwazza** [comment]
There's examples of creating indexes in DI in the `Examine.Web.Demo.IndexFactoryExtensions.CreateIndexes` which is used in Startup.cs. Else there's more examples in the umbraco netcore project too.
