### ISSUE TITLE
OrderBy double values sorts only by decimal places.

### ISSUE THREAD

**Issue by deekoulos** [Shazwazza/Examine#242]
Hi there,

using version 1.2.2 and experiencing a weird sorting when I use orderByDescending double values.

For instance: if we have the following values:

5.0
4.9
4.5
3.9
3.8
2.6

and we want to order them descending, its ordering based on the decimal places and ignores the digits left to the "." 
Result:

4.9
3.9
3.8
2.6
4.5
5.0

excepted result:
5.0
4.9
4.5
3.9
3.8
2.6

I am using Umbraco fields of type decimal, which are queried via examine index and then sorted wrongly as above.

Does anyone else have the same issue?

I somehow think this was working fine in the past and after the last upgrade from I guess 1.1.0 to 1.2.2 the issue is showing up.

This is the code I am using:

```
sortedBooleanOperation = booleanOperation                
                .OrderByDescending(new SortableField("approvedOverallRating", SortType.Double))
                .OrderByDescending(new SortableField("approvedRatingCount", SortType.Int))
                .OrderByDescending(new SortableField("googleRating", SortType.Double))
                .OrderByDescending(new SortableField("googleRatingsTotal", SortType.Int));
```

**Comment by deekoulos** [comment]
Hey Shannon,

this is how I register all custom fields:

```
    public class ConfigureIndexComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            // replace the default IUmbracoIndexConfig definition
            composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();
        }
    }

    // inherit from the default
    public class CustomIndexConfig : UmbracoIndexConfig, IUmbracoIndexConfig
    {
        public CustomIndexConfig(IPublicAccessService publicAccessService) : base(publicAccessService)
        {
        }

        // explicit implementation - overrides base class.
        // GetMemberValueSetValidator is used for the MemberIndex.
        IValueSetValidator IUmbracoIndexConfig.GetMemberValueSetValidator()
        {
            // include everything except the above
            return new MemberValueSetValidator(null, null, null, null);
        }
    }
```

The thing is, it always worked properly, since launching the website 10 months ago. I also worked well before the last upgrade and I didn't change the code regarding lucene or sorting for a long time. 

The only changes I had were upgrading umbraco from 8.10.3 to 8.14.3 and Examine from 1.1.0 to 1.2.2. I am not sure if I was using Examine 1.0.6 or 1.1.0. but I am sure it worked properly in the past, because this is the crucial part of the platform, to sort the members based on their ratings (decimal) and then the total number of the ratings (int).

**Comment by deekoulos** [comment]
update: 

locally I am facing the same issue after the upgrade. So, I downgraded Examine from 1.2.2 back to 1.1.0 and it also downgraded Umbraco from 8.14.3 to 8.13.1 automatically. After running the solution locally and rebuilding the index, the sorting issue is gone. Its sorting properly again on all those fields in the correct order and its also sorting properly based on multiple fields in the right order. 

So now, running Umbraco 8.13.1 and Examine 1.1.0 the application sorts the members exactly in this way on multiple fields in the right order:

```
sortedBooleanOperation = booleanOperation                
                .OrderByDescending(new SortableField("approvedOverallRating", SortType.Double))
                .OrderByDescending(new SortableField("approvedRatingCount", SortType.Int))
                .OrderByDescending(new SortableField("googleRating", SortType.Double))
                .OrderByDescending(new SortableField("googleRatingsTotal", SortType.Int));
```

**Comment by deekoulos** [comment]
update:

the sorting issue is coming with examine version 1.2.1

I upgraded from 1.1.0 to 1.2.0, rebuilt the solution, rebuilt the index, sorting was still working properly. After upgrading to 1.2.1 the issue described above occurs.

**Comment by deekoulos** [comment]
@Shazwazza  regarding your answer, that we can't sort by multiple fields, pls take a look at this issue, where u mentioned that it is possible:

https://github.com/Shazwazza/Examine/issues/97

**Comment by Shazwazza** [comment]
@deekoulos thanks, maybe I'm thinking of sorting with score + a field. Do you have time to help out? Writing a unit test is very easy

**Comment by deekoulos** [comment]
@Shazwazza  were you able to find any related changes within 1.2.1 which could be the cause of the issue?

**Comment by Shazwazza** [comment]
Here is a new test: `Sort_Result_By_Double_Fields` which passes https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L1256

what you describe here:

> and we want to order them descending, its ordering based on the decimal places and ignores the digits left to the "."

Is consistent with the field not actually being `Double` since it's being sorted by its string representation. 

Above you mention that you use `IUmbracoIndexConfig` to customize the fields, but this service is not used to customize fields. That's purely to return different validators for each index. 

Can you please post the code that you are using to customize the index? Any field customizations that occur after the index has been initialized will not be carried through - as noted here: https://shazwazza.github.io/Examine/configuration under V1:

> It is possible to add custom field value types after the construction of the index, but this must be done before the index is used. Some people may prefer this method of adding custom field value types. Generally, these should be modified directly after the construction of the index.

> The thing is, it always worked properly, since launching the website 10 months ago. It also worked well before the last upgrade and I didn't change the code regarding lucene or sorting for a long time.

Depending on many things, it is possible that some code can be triggering index initialization before your field definitions are applied. This is a known issue in Umbraco that is supposed to be recently fixed, you can read about it here: https://github.com/umbraco/Umbraco-CMS/issues/8893. You can also try this out https://github.com/umbraco/Umbraco-CMS/issues/8893#issuecomment-910828242

**Comment by Shazwazza** [comment]
I've also added a multiple field sorting test `Sort_Result_By_Multiple_Fields` which passes https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L1306

**Comment by deekoulos** [comment]
We don't modify the index at all. In the past, I did this just as mentioned in the documentation here:

https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/#changing-field-value-types

But it forced us to rebuild the index in the code to get it work and therefore we removed the index customizations. 

And also in the documentation above there is a comment above the line where the existing fields get modified:
![image](https://user-images.githubusercontent.com/55948134/132008633-f8e735ac-2ea2-4d61-b9b9-f8dfa9e45d10.png)

The comment says "not recommended". This is why we thought this is not the best approach and maybe this is why the index needs to be rebuilt in code after modifiying it. 

The weird thing is, again, it all works properly until version 1.2.0. Version 1.2.1 is causing the above issues.

Regarding the sorting based on strings and not real double values, I just wrote this piece of code to demonstrate, that even decimal values as strings, both with . and , separated, are getting sorted properly:

```
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            List<string> doubleStrings = new List<string>
            {
                "3.8",
                "5.0",
                "4.7",
                "2.9",
                "4.0"
            };

            List<string> doubleStringsWithComma = new List<string>
            {
                "3,8",
                "5,0",
                "4,7",
                "2,9",
                "4,0"
            };

            foreach (var item in doubleStrings)
                Console.WriteLine(item);

            Console.WriteLine("");

            foreach (var item in doubleStrings.OrderByDescending(x => x))
                Console.WriteLine(item);

            Console.WriteLine("");

            foreach (var item in doubleStringsWithComma.OrderByDescending(x => x))
                Console.WriteLine(item);
        }
    }
}
```
![image](https://user-images.githubusercontent.com/55948134/132009870-5d878855-9e11-4229-8a63-2dd0a2b009d9.png)

I don't know why the lucene engine stopped sorting the string values differently in examine version 1.2.1.

**Comment by Shazwazza** [comment]
The comment in the docs says:

> // modify an existing field type (not recommended)

Meaning - it is not recommended to modify an existing (built in) field that Umbraco manages such as `parentID`

> But it forced us to rebuild the index in the code to get it work and rebuilding the index in code caused other issues, locked states and so on. Therefore we removed the index customizations.

Customizing fields in the index is a normal procedure. Yes, initially you will have to rebuild the index because any pre-existing index that was built without the field customizations will of course not have those customizations. Not sure why you would get other issues but if you can reproduce then please log an issue on the Umbraco tracker with steps to reproduce.

I've added more test cases and they all pass, see: https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L1261

I would highly recommend configuring any fields that you want to be sortable as actually sortable field types, else it will probably only work by pure fluke. The sorting docs are here: https://shazwazza.github.io/Examine/sorting
