### ISSUE TITLE
Index empty after rebuild

### ISSUE THREAD

**Issue by Sophiehillebrant** [Shazwazza/Examine#245]
We are facing an issue with a project that implements Ucommerce. We have created an index for all of our products from Ucommerce, with a populator to specify properties via a UCommerceValueSetBuilder. 
Rebuilding the index from the Examine Management UI works well but when we try to rebuild the index programatically, as part of a scheduled job, after we have imported new products into ucommerce, the rebuild fails, and the index is left empty. 

Have isolated the exception we're getting to this specific line: 
indexRebuilder.RebuildIndex("UcommerceIndex");

Exception message:
"Queue is empty"

Stack trace: 
"  at Examine.LuceneEngine.OpenReaderTracker.CloseStaleReaders(Directory dir, TimeSpan ts)\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.EnsureIndex(Boolean forceOverwrite)\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.CreateIndex()\r\n   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName)\r\n   at KxsSva.Ucommerce.Controllers.ApiControllers.ImportController.<StartProductImportAsync>d__6.MoveNext() in C:\\Projekt\\SVA\\KxsSva.Ucommerce\\Controllers\\ApiControllers\\ImportController.cs:line 45"

Not really sure which other info is relevant to provide so please let me know.
Any help appreciated as this is causing us to have to rebuild the index through Examine Management each time the scheduled job has run.

**Comment by Shazwazza** [comment]
I think that is this bug https://github.com/Shazwazza/Examine/issues/220 which is fixed. Please make sure you are running the latest Examine version.

**Comment by Sophiehillebrant** [comment]
We are at version 1.2.0 right now, but can't seem to upgrade to latest (2.0.0) as it is not compatible with UmbracoCms.Web latestversion? Dependency says it supports Examine 1.2.0 < 1.99999...
Should I just upgrade to 1.2.2 then?

**Comment by Shazwazza** [comment]
Correct. Version 2 is not compatible with Umbraco 8 which is why it has that restriction. You should just use the latest 1.x version.
