### ISSUE TITLE
Cannot retrieve approved members

### ISSUE THREAD

**Issue by deekoulos** [Shazwazza/Examine#246]
Hi there,

there is a default property named "umbracoMemberApproved" which is set to true or false, if you switch the default "Approved" toggler of the member type accordingly:

![image](https://user-images.githubusercontent.com/55948134/133939858-d9bde0a4-ee82-42e1-820c-0e05a6453383.png)

In the past we could retrieve the approved members by applying this filter, which worked properly:

```
if (!ExamineManager.Instance.TryGetIndex(Umbraco.Core.Constants.UmbracoIndexes.MembersIndexName, out IIndex index) || !(index is IUmbracoIndex))
                throw new InvalidOperationException("The required index MemberIndex was not found");

            var booleanOperation = index.GetSearcher()
                .CreateQuery("member", BooleanOperation.And)
                .Field("published", "1")
                .And().Field("umbracoMemberApproved", "1")
                .OrderByDescending(new SortableField("nodeName", SortType.String));
```

Now that we are using the current version of Examine 1.2.2 and Umbraco 8.15.3 this is not working anymore.

Even when we try the member examine search in the umbraco backoffice, we can't find the approved members either, although there are members with this property set to true (1):

![image](https://user-images.githubusercontent.com/55948134/133939776-21d7b4ef-8c47-422e-b05c-96205abe658d.png)

![image](https://user-images.githubusercontent.com/55948134/133939788-44696c02-4803-4e30-8776-0c63054fc099.png)

querying like propertyname:1 works for other properties like "published", but not for approved:

![image](https://user-images.githubusercontent.com/55948134/133939825-09ec9495-0857-4ca2-91f6-514e8bcf6172.png)

**Comment by Shazwazza** [comment]
Umbraco by default only indexes a few fields, this is defined by Umbraco's `MemberValueSetValidator` https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Examine/MemberValueSetValidator.cs#L26

You can replace this to index other fields. Even though some fields may exist in your index (assuming this is an upgraded site or something, and that is why this data still exists there), it will not search on those fields if they are not known. 

If you replace the MemberValueSetValidator and add that additional field, it will work. 

If you think this is an issue and this should be included by default, please open an issue on the Umbraco tracker.

**Comment by deekoulos** [comment]
Thank you for your response.

This is then indeed an issue for us. Because we have a lot of custom member properties, which are included this way:

```
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class ConfigureIndexComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            // replace the default IUmbracoIndexConfig definition
            composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();
        }
    }

    // inherit from the default
    public class CustomIndexConfig : UmbracoIndexConfig, IUmbracoIndexConfig
    {
        public CustomIndexConfig(IPublicAccessService publicAccessService) : base(publicAccessService)
        {
        }

        // explicit implementation - overrides base class.
        // GetMemberValueSetValidator is used for the MemberIndex.
        IValueSetValidator IUmbracoIndexConfig.GetMemberValueSetValidator()
        {            
            // include everything except the above
            return new MemberValueSetValidator(null, null, null, null);
        }
    }
```

If I understand this right: 
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Examine/MemberValueSetValidator.cs#L26

We need to define all available fields and also include the default system fields and pass it as the 3rd parameter to the MemberValueSetValidator, which is not a best practice. 

Umbraco should at least index it's own default fields. 

Do you have another idea how to achieve the goal? We have more than 100 custom fields.

**Comment by Shazwazza** [comment]
This validator class is what filters fields. If you specify fields to include - like Umbraco does, then it will only include those fields and ignore everything else. Else, you can specify fields to exclude, in which case it will index everything except for certain fields. Member data can contain sensitive information so Umbraco only indexes a minimal amount. 
You can work around this by using your own validator and filter the fields that you want.

**Comment by deekoulos** [comment]
are you sure that the umbracoMemberApproved field is not index, when we use

`return new MemberValueSetValidator(null, null, null, null);`

? As far as I know, if you set all 4 parameters with null, all available fields are getting indexed. And if they were not indexed, then they wouldn't be visible either in the backoffice search results. but in our case, all these fields are available with values:

![image](https://user-images.githubusercontent.com/55948134/134054964-580e9642-4b30-474a-bc60-b495af9c234d.png)

And as already mentioned, I always used umbracoMemberApproved:1 and could filter the approved ones.

Shannon, please take a deeper look into this. I am pretty sure, that this behaviour is new and by passing null, null, null, null to the validator, all available system and custom fields get indexed.

**Comment by deekoulos** [comment]
@Shazwazza I just recorded the screen to show you what I mean. Please set to volume on:

https://share.vidyard.com/watch/PKfUShc7MMM1BUDFmgpc8n?

**Comment by Shazwazza** [comment]
Sorry just realized you mentioned above. To confirm, you do use this?

> return new MemberValueSetValidator(null, null, null, null);

**Comment by Shazwazza** [comment]
I just tested again using `return new MemberValueSetValidator(null, null, null, null);`

All properties are indexed and `umbracoMemberApproved:1` is working see: https://user-images.githubusercontent.com/1742685/134062840-ec07cb60-2701-4812-aa2f-808b6341b64b.MP4

**Comment by deekoulos** [comment]
I found the root cause. please take a look here: 

https://share.vidyard.com/watch/1VexBJxAohYsoXYQLH1sMo?

this is causing the issue. Like already mentioned here: https://github.com/Shazwazza/Examine/issues/242#issuecomment-912525551 modifying the fields causes weird issues. 

```
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    // register the component
    public class CustomizeIndexComposer : ComponentComposer<CustomizeIndexComponent> { }

    public class CustomizeIndexComponent : IComponent
    {
        private readonly IExamineManager _examineManager;
        private readonly IndexRebuilder _indexRebuilder;

        public CustomizeIndexComponent(IExamineManager examineManager, IndexRebuilder indexRebuilder)
        {
            _examineManager = examineManager;
            _indexRebuilder = indexRebuilder;
        }

        public void Initialize()
        {
            if (!_examineManager.TryGetIndex(Constants.UmbracoIndexes.MembersIndexName, out IIndex index))
                return;

            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("umbracoMemberApproved", FieldDefinitionTypes.Integer));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("memberGroups", FieldDefinitionTypes.FullTextSortable));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("approvedOverallRating", FieldDefinitionTypes.Double));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("approvedRatingCount", FieldDefinitionTypes.Integer));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("googleRating", FieldDefinitionTypes.Double));
            index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("googleRatingsTotal", FieldDefinitionTypes.Integer));

            //var luceneIndex = index as LuceneIndex;
            //var dir = luceneIndex.GetLuceneDirectory();
            //if (IndexWriter.IsLocked(dir))
            //    IndexWriter.Unlock(dir);

            //_indexRebuilder.RebuildIndex(index.Name);
        }

        public void Terminate() { }
    }
```

**Comment by Shazwazza** [comment]
Lol, i have no idea why that recorded upside down.

But yes, you are marking it as a numerical field. This is fine so long as you are searching on it like a numerical field. Else you need to use a range query in the editor like umbracoMemberApproved:[1 to 1] (see range searches https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)

**Comment by Shazwazza** [comment]
The Examine APIs will search on a numerical number for you so long as you are using the correct methods.  For example, you are using: `.And().Field("umbracoMemberApproved", "1")` which will not pass that into the numerical field, you should do `.And().Field("umbracoMemberApproved", 1)`

**Comment by deekoulos** [comment]
you made my day!

I just removed this line: 

`index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("umbracoMemberApproved", FieldDefinitionTypes.Integer));`

and let the field be sorted as a string, since it only can be 0 or 1, sorting by string has the same effect as an integer and the issue is gone!

Big Thanks, one again, Shannon!

**Comment by Shazwazza** [comment]
Nice, glad you got it resolved 💪
