### ISSUE TITLE
Examine dataservice

### ISSUE THREAD

**Issue by Sonic3R** [Shazwazza/Examine#248]
I work on custom examine indexer to grab some data from outside of Umbraco content

I have ExamineSettings.config:

```
<add name="myIndexer" type="Examine.LuceneEngine.Providers.SimpleDataIndexer, Examine"
     autoOptimize="false"
     indexSet="myIndexSet"
     dataService="MyNamespace.ThisIsMyIndexDataService, MyNamespace"
     analyzer="MyNamespace.MyAnalyzer, MyNamespace"
     indexTypes="aliasName"/>
```

But for custom `dataService` I don't know how to implement since in old version of Examine I could use `ISimpleDataService` but it is not available anymore in newer version for Examine library.

What interface/class should implement/use ?

**Comment by Shazwazza** [comment]
Examine doesn't know about data sources like it did in 0.x versions. It only knows how to index something that you tell it to. So you are in charge of implementing a data source to produce `ValueSet`s to pass to Examine for indexing if you are rebuilding from scratch. 

Examine docs are here https://shazwazza.github.io/Examine/
