### ISSUE TITLE
Sorting Issue with multiple fields.

### ISSUE THREAD

**Issue by Attackmonkey** [Shazwazza/Examine#249]
I have an Umbraco Examine external index that we use for searching. Previously everything was ordered by Name, using a custom field that was full text indexable, and that worked fine.

We've now added an option to show records with a boolean set to true (or "1" because it's Lucene) first, and we want to then sub-order by name, as we did previously.

First I tried something like this:

`searchResultsQuery = nativeQuery.OrderByDescending(new SortableField(request.BaseQuery.OrderByAlias, SortType.String)).OrderBy(new SortableField(IndexingFieldNames.CompanyName, SortType.String));`

This correctly ordered with the booleans first, but the second order by didn't work. It DID change the order slightly, just not to alphabetical ascending like we expected.

After a chat with Callum Whyte, we tried adding to the sort collection directly using something like:

`var test = criteria as Examine.LuceneEngine.Search.LuceneSearchQuery;`
`test.SortFields.Add(new Lucene.Net.Search.SortField(request.BaseQuery.OrderByAlias, Lucene.Net.Search.SortField.STRING, true));`
`test.SortFields.Add(new Lucene.Net.Search.SortField(IndexingFieldNames.CompanyName, Lucene.Net.Search.SortField.STRING, false));`

That basically did the same as the first example code. Ordered by the boolean OK, just not the alphabetical second clause.

Finally, I wondered if it was the different sort directions, so I tried ordering vy multiple columns in the same direction:

`searchResultsQuery = nativeQuery.OrderByDescending(new SortableField(request.BaseQuery.OrderByAlias, SortType.String), new SortableField(IndexingFieldNames.CompanyName, SortType.String));`

But that yielded similar results to the other examples.

I'm not sure if this is a bug, or if we're doing something wrong somewhere. But the alphabetical ordering works as expected if we JUST order by the one column.

As a temporary workaround, we've added a custom index field and just sorted by that, but it would be good to know if what we're doing isn't possible (in which case it'd be worth adding to the docs), or if it's actually a bug!

**Comment by Shazwazza** [comment]
It would probably be easiest if you are able to clone this repo and create a unit test for what you are trying/expecting. There are already tests in there for multiple field sorting but perhaps your scenario is different https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L1313

**Comment by Attackmonkey** [comment]
Thanks @Shazwazza, in my case it's sorting numbers and also text. In the current tests it's just testing multiple sort with numbers baby the look of it. I'll clone the repo and set up some test cases for our examples, so we can see if we can replicate the issue! I'll keep you updated.

**Comment by Attackmonkey** [comment]
OK, have added a bunch of tests and they all pass as expected. So it must be something else causing the ordering to be off. Any ideas on the best places to look so I can log more detail if it does turn out to be an Examine issue? It's an Umbraco V8 site index that's displaying the issue, so I'm not sure if there's anywhere in the Umbraco codebase I should be looking too?

**Comment by Attackmonkey** [comment]
OK, I've tracked this one down, it was an issue with the data in the indexes rather than an Examine issue. It looks like some of the records were missing one of the fields used in the sort, causing them to not get ordered correctly and appear in random places in the order.

**Comment by Shazwazza** [comment]
Glad you resolved it. Some sorting docs are here https://shazwazza.github.io/Examine/sorting
