### ISSUE TITLE
Is Fuzzy working correctly?

### ISSUE THREAD

**Issue by sayeduzzamancuet** [Shazwazza/Examine#252]
Does examine support sound a like search and Jaro winkler search?
The fuzzy search seems not that much accurate and returns all data ignoring the float value.

**Comment by Shazwazza** [comment]
Hi, yes this project is very much alive and active, you can see the releases on nuget: https://www.nuget.org/packages/Examine

The examine docs are here: https://shazwazza.github.io/Examine/

Examine is a searching/indexing API abstraction which by default is implemented with Lucene. If you require specialized searching and indexing that are not available through the Examine APIs then you would need to use the underlying engine (i.e. Lucene) directly.

**Comment by sayedgt** [comment]
@Shazwazza  
```
filter.Or(query => query.GroupedOr(new []{ "firstName","lastName" }, namePart.ToLower().Fuzzy(.7F)));
```
this is generating 
```
{ Category: , LuceneQuery: (+(firstName:ahmed~1 lastName:ahmed~1))}
```

**Comment by Shazwazza** [comment]
I'm investigating this now, i'll report back soon.

**Comment by Shazwazza** [comment]
So the way Lucene.NET works internally is it converts the float number to the corresponding INT value based on this method https://lucenenet.apache.org/docs/4.8.0-beta00005/api/Lucene.Net/Lucene.Net.Search.FuzzyQuery.html#Lucene_Net_Search_FuzzyQuery_SingleToEdits_System_Single_System_Int32_

The fuzzy query syntax in Lucene 4.x+ doesn't actually use floats, it uses INT but the source code still supports the float values in the QueryParser (probably mostly for backwards compat). The INT values for fuzzy searches is a number between 0 and 2.

So the float value that you are passing in get converted to INT (anything from 0 to 2) which depends on the word specified and the float value you are using.

So the underling logic is working as expected as far as Lucene goes. You can read more about Fuzzy queries here https://lucenenet.apache.org/docs/4.8.0-beta00005/api/Lucene.Net/Lucene.Net.Search.FuzzyQuery.html#Lucene_Net_Search_FuzzyQuery_SingleToEdits_System_Single_System_Int32_

**Comment by sayeduzzamancuet** [comment]
@Shazwazza  so in lucene there is no way to search using minimum similarity score right now(like minimum 70%)? It only supports upto 2 edit distance?
