### ISSUE TITLE
Q: How to use 'ExamineManager.Instance.ReIndexNode()' with custom data?

### ISSUE THREAD

**Issue by hfloyd** [Shazwazza/Examine#27]
Hi!
I've got a custom (non umbraco) Indexer set up and working properly by looping through my custom data and creating a "SimpleDataSet" for each item. Now I am adding functionality to update the index when operations happen on the custom objects. 

I have successfully set up a "Remove from Index" function to run on object delete by looking up the index nodeId for the object, and passing it to 'ExamineManager.Instance.DeleteFromIndex(...)'

Now I'd like to add operations to run on object create and update which would add just the current object to the index. I was looking at 'ExamineManager.Instance.ReIndexNode()' which expects an "XElement" as the representation of the index data, but I am unclear what format that needs to be in, or how to convert a SimpleDataSet into an XElement.

Is it possible to only index a single object? I'd rather not have to run 'ExamineManager.Instance.IndexAll()' every time something is added or changed... But perhaps that isn't possible?

**Comment by Shazwazza** [comment]
Unfortunately the way that Examine was original make (a very long time ago) was based on the Xml for Umbraco and therefore it has the strange API that makes you pass in an XML structure.

There's a few extension methods in Examine you can find here:

https://github.com/Shazwazza/Examine/blob/master/Projects/Examine/LuceneEngine/ExamineXmlExtensions.cs

That can convert dictionaries or whatever into the correctly formatted XML to be passed in to the ReIndex node method.

**Comment by Shazwazza** [comment]
You can also see an example in the web proj demo in source here: https://github.com/Shazwazza/Examine/blob/master/Projects/Examine.Web.Demo/Controllers/HomeController.cs#L119

**Comment by hfloyd** [comment]
Thanks, Shannon, I ended up using the ".ToExamineXml" extension on SimpleDataSet.RowData.

My final solution is here: our.umbraco.org/forum/developers/api-questions/68296-how-to-use-examinemanagerinstancereindexnode-with-custom-data#225622
