### ISSUE TITLE
Bug? Exact Examine query not searching exactly

### ISSUE THREAD

**Issue by V414** [Shazwazza/Examine#273]
_I initially encountered this issue on Umbraco v1.17.2, which I believe used Examine v1.2.1. To try and fix it, I upgraded Umbraco to v1.18.0, which uses Examine v1.2.2, but sadly the issue remains._

In brief, I am trying to search for an exact tag name using Examine, and some of these tags have spaces between. However, no matter what I do, Examine is returning results based on the first word not the entire exact query.

For example, if I am trying to search for a tag called "Test Tag", if I use an Examine query of "Test" is still shows content marked with the "Test Tag". 

After looking through the documentation, I tried using the .Escape() method on my query, because it sounds like it should do what I want, but that unfortunately did work either.

I don't think it is anything I've done on my end, because it happens when using the raw query within the Umbraco examine index. (e.g. +PolicyCategoryTags:"Government" returns content marked "Local Government"). 

I've even tried using hyphens and underscores to separate the words instead of spaces, with the same result.

Am I missing something, or is this a bug within Examine? It feels like there should be some way I can search for a multi word tag without returning other tags...

**Comment by Shazwazza** [comment]
Can you please post steps to replicate the issue? 

Also, please see the FluentApiTest cases for many searching examples. For example, here

https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L1431
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L51

**Comment by V414** [comment]
Hey, thanks for replying!

[https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L1431](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L1431)

This is exactly what I have tried in Umbraco, but exact "" searched don't seem to be working as expected when searching with part of other phrases.

For example, if I search only "codegarden" or "09" it will also return content that have additional words in, like "codegarden 09", even though I only want content with that exact word or phrase in. 

Another way of putting it - searching this:

`
                var sc = searcher.CreateQuery("content").Field("nodeName", "codegarden".Escape());
`

Seems to return all content which contain that word, so things like "codegarden 09" are valid results, as are "codegarden 01 01", or "test codegarden", etc.

**Comment by V414** [comment]
I think I have found a more visual way of explaining the problem:

![Examine search 1](https://user-images.githubusercontent.com/3150585/160157693-9d45a2e8-e387-49d1-a8d7-5bbc482709f7.png)

The above picture correctly searches for the name "test", and includes all results that contain that word.

However, the next search, although it uses an exact search (uses the quotations), shows exactly the same results - when it should limit them to only things that contain that exact term right?

![Examine search 2](https://user-images.githubusercontent.com/3150585/160157969-26a484cf-d5bb-4473-ba15-8e9d076e59d0.png)

**Comment by Shazwazza** [comment]
Hi, I think there's some confusion here over what a search does. The screenshots above are correct, you are just searching for the word 'test' in both cases. Putting quotes around a term just means it will search for that phrase, it doesn't mean it will exclude all results that are not that exact text.

What I think you are asking for is to match a field that is the exact match of your search term and if it is not exactly 100% that entire field it is not returned? If that is the case, that requires the field to be analyzed differently (probably with the keyword analyzer), however that will mean that if you want single word or phrase matches (as is the default in searching) then you would need to store this field twice, one with the normal analyzer and another with the keyword analyzer. See https://stackoverflow.com/questions/36077593/match-lucene-entire-field-exact-value
