### ISSUE TITLE
How to do MLT (More Like This) searches?

### ISSUE THREAD

**Issue by karlmacklin** [Shazwazza/Examine#274]
Lucene has a concept called More Like This, "MLT":
https://lucene.apache.org/core/7_2_0/queries/org/apache/lucene/queries/mlt/MoreLikeThis.html

Is it possible to do similar searches via Examine?
If so, is there any example anywhere on how to perform such a search?

**Comment by Shazwazza** [comment]
Hi, Examine does not support this with its own APIs but Examine exposes the underlying Lucene APIs that you can use to make it work, however, this depends on the lucene version. For Examine 2 which uses Lucene 4.8.x this is possible, but Examine 1 uses Lucene 3.x and as far as I know this is not available in the old lucene version. 

The 4.8 docs for this are here https://lucenenet.apache.org/docs/4.8.0-beta00014/api/queries/Lucene.Net.Queries.Mlt.html

What Examine version are you using?

**Comment by NightOwl888** [comment]
@Shazwazza 

Actually, there is a `MoreLikeThis` and `MoreLikeThisQuery` in the [Lucene.Net.Contrib module](https://www.nuget.org/packages/Lucene.Net.Contrib/): 
- https://github.com/apache/lucenenet/tree/Lucene.Net_3_0_3_RC2_final/src/contrib/Queries/Similar

So, this is also available in Lucene.NET 3.0.3 and 2.9.4.1.

- https://lucenenet.apache.org/docs/3.0.3/dd/dd0/class_lucene_1_1_net_1_1_search_1_1_similar_1_1_more_like_this.html

> Looks like the 2.9.4 docs are broken, though - I can see `MoreLikeThis` in the TOC (`Lucene.Net.Search.Similar` namespace), but the link doesn't respond when clicked. In fact, none of the TOC links seem to work.

**Comment by NightOwl888** [comment]
> Looks like the 2.9.4 docs are broken, though - I can see `MoreLikeThis` in the TOC (`Lucene.Net.Search.Similar` namespace), but the link doesn't respond when clicked. In fact, none of the TOC links seem to work.

Correction - looks like it just isn't working in Edge. It seems to work fine in Chrome.

https://lucenenet.apache.org/docs/2.9.4/html/89cb8710-1d51-ce77-326e-60c7a6862b9d.htm

**Comment by karlmacklin** [comment]
This is a new project, so basically I'm on the latest version inside the latest Umbraco version.

We'll try with Native Queries!

**Comment by Shazwazza** [comment]
Hi @karlmacklin Native Queries with Examine won't help with MLT. All that is enabling you to do is use lucene query syntax to do your searches.

To do MLT searching you will need access to the underlying `IndexSearcher` which you can do like:

```cs
var searcher = (LuceneSearcher)indexer.Searcher;
var searchContext = searcher.GetSearchContext();

using (ISearcherReference searchRef = searchContext.GetSearcher())
{
     var luceneIndexSearcher = searchRef.IndexSearcher;

     // ... now you can use the underlying lucene searcher instance

}
```
