### ISSUE TITLE
Query strings containing lucene-recognizable boolean operators causes QueryParseException.

### ISSUE THREAD

**Issue by dunkmaster** [Shazwazza/Examine#28]
I don't know if this is a known issue, but: 

Query strings containing lucene-recognizable boolean operators causes QueryParseException.
These include: (!, ||, &&, NOT, OR, AND).

Example from our.umbraco.org: https://our.umbraco.org/search?q=OR
The same happends with other umbraco sites using examine.

**Comment by Shazwazza** [comment]
I guess it's known, passing in an invalid raw query will always cause a YSOD. not really an issue with Examine, it's an issue with it's usage. Examine can't really stop you from entering an invalid query.
