### ISSUE TITLE
[3.0.0-beta9] TryAdd is missing in ValueSet

### ISSUE THREAD

**Issue by skttl** [Shazwazza/Examine#281]
I was trying to upgrade FullTextSearch to support Umbraco 10 (and Examine 3.0.0). In this package I [add fields to the external index](https://github.com/skttl/umbraco-fulltextsearch8/blob/v9/dev/src/Our.Umbraco.FullTextSearch/NotificationHandlers/AddFullTextItemsToIndex.cs#L126), but my upgrade attempt failed because ValueSet no longer has the [TryAdd](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Core/ValueSet.cs#L240) method.

Am I supposed to add fields in another way now, or will TryAdd come back?

**Comment by Shazwazza** [comment]
Hi, please see this ticket for info on ValueSet changes: https://github.com/Shazwazza/Examine/issues/276 and why it's immutable now. See the mentioning of the SetValues method on the event args.

**Comment by skttl** [comment]
Thanks, I missed that! I got it working now :)
