### ISSUE TITLE
StackOverflow Exception when running v0.1.67 with Umbraco v7.2.8

### ISSUE THREAD

**Issue by danlister** [Shazwazza/Examine#29]
I previously had an Umbraco v7.2.8 installation running with Examine v0.1.66 for a while now. After upgrading Examine to v0.1.67, the application fails to start with the following exception occurring every 30 seconds or so.

<img width="485" alt="screen shot 2015-08-12 at 15 17 29" src="https://cloud.githubusercontent.com/assets/596453/9226670/95f12222-4107-11e5-8221-e3b702ecb2ce.png">

In order to reproduce the error, create a v7.2.8 installation of Umbraco and upgrade it's Examine Nuget package to v0.1.67. When navigating to the site for the first time, the above exception should occur. When navigating to the site, the Examine indexes folder should be deleted prior to navigating to replicate. To fix, I have downgraded the Examine Nuget package to v0.1.66 which seems to allow the application to start correctly. 

I understand this is probably not that much to go off. I've have checked Umbraco's log files and my system's Event Logs and nothing is logged relating to the exception. I can replicate this using a fresh install of Umbraco via Nuget. I'm guessing the issue will be related to the following changes.

https://github.com/Shazwazza/Examine/compare/v0.1.66...v0.1.67

The exception occurs within LuceneIndex.cs according to Visual Studio:

<img width="511" alt="screen shot 2015-08-12 at 15 53 38" src="https://cloud.githubusercontent.com/assets/596453/9227218/559d0d1e-410a-11e5-9af6-89f3b211a0d3.png">

**Comment by Shazwazza** [comment]
thanks, i'll have a look

**Comment by Shazwazza** [comment]
i think i can repro, for now i'll unlist that examine version.

**Comment by Shazwazza** [comment]
Thanks for reporting, i can replicate. I hastily deployed this new version on Friday without testing the last change made. OOPS many appologies. Will deploy a new version today,.

**Comment by Shazwazza** [comment]
This is fixed now, i'll release a new version tonight or tomorrow.

**Comment by danlister** [comment]
Thanks @Shazwazza! Thats one awesomely quick turnaround :+1:
