### ISSUE TITLE
Support `DateOnly` in range query

### ISSUE THREAD

**Issue by bjarnef** [Shazwazza/Examine#314]
Currently it seems `DateOnly` doesn't work in range query, while `DateTime` does.

```
public void Configure(string name, LuceneDirectoryIndexOptions options)
{
    switch (name)
    {
        case Umbraco.Cms.Core.Constants.UmbracoIndexes.ExternalIndexName:
            options.FieldDefinitions.TryAdd(new FieldDefinition(UmbracoExamineFieldNames.NodeNameFieldName, FieldDefinitionTypes.FullTextSortable));
            options.FieldDefinitions.TryAdd(new FieldDefinition(Constants.Examine.Course.FieldNames.CategoriesCount, FieldDefinitionTypes.Integer));
            options.FieldDefinitions.TryAdd(new FieldDefinition(Constants.Examine.Course.FieldNames.ExpirationDate, FieldDefinitionTypes.DateTime));
            break;
    }
}
```

and

```
if (expiryDate.HasValue)
{
      query.And().RangeQuery<DateOnly>(new[] { SearchField.Course.ExpirationDate },
          expiryDate.Value,
          DateOnly.MaxValue,
          minInclusive: true);
}
```

![image](https://user-images.githubusercontent.com/2919859/203067595-605e9e08-759f-44a4-8c9f-48ad39850f03.png)

However if I use `DateTime` instead of `DateOnly` it works.

```
if (expiryDate.HasValue)
{
      query.And().RangeQuery<DateTime>(new[] { SearchField.Course.ExpirationDate },
          expiryDate.Value,
          DateTime.MaxValue,
          minInclusive: true);
}
```

I guess it should have a  `DateOnlyType.cs` here: https://github.com/Shazwazza/Examine/tree/07d0889d6d0a9ea06b9bae34a068dcb959e3322f/src/Examine.Lucene/Indexing

**Comment by bjarnef** [comment]
Should we also support `TimeOnly` in .NET6+?
https://medium.com/@niteshsinghal85/converting-dateonly-and-timeonly-to-datetime-and-vice-versa-in-net-6-72db56853857

**Comment by nikcio** [comment]
Hi @bjarnef I've looked a bit into this and this can be done without creating a new indexing method and by modifying `RangeQueryInternal` instead see #315 

I don't know if `TimeOnly` makes much sense to solve in this way because then which day should then be used so this might require new indexing to work properly.

**Comment by bjarnef** [comment]
@nikcio okay great ;)
Not sure about `TimeOnly` but I guess is could use any date, like date of `DateTime.Min` (which is default date of `DateTime`).

Or it could use the ticks as `int` or `long` value. I think it was the old way to handle sorting of `DateTime` in Examine, but now it works using `DateTime` OOTB. I only needed to define custom datetime properties as datetime as it is fulltext by default.
