### ISSUE TITLE
Combination of MultipleCharacterWildcard() with Boost() not possible

### ISSUE THREAD

**Issue by Sven883** [Shazwazza/Examine#316]
Hello!

I've been searching for a while now how to combine MultipleCharacterWildcard() with Boost() on an umbraco 9 installation.
I've tried adding it by doing the following things:
-` $"{searchQuery}*".Boost()` -> doesn't work, boost() seems to delete the '*' char 
- following https://our.umbraco.com/forum/using-umbraco-and-getting-started/107135-is-there-a-way-to-include-a-wildcard-in-an-examine-nativequery-call#comment-333561 -> doesn't work since boost is a readonly property.
- Hacky way, but I tried: `var luceneQuery = examineQuery.ToString().Replace("^", "*^");` and using it in a nativeQuery:
`nativeQuery = searcher.CreateQuery(IndexTypes.Content).NativeQuery(luceneQuery);` -> Problem with parsing:

```
Lucene.Net.QueryParsers.Classic.ParseException: Cannot parse '{ Category: content, LuceneQuery: +__NodeTypeAlias:vacancypage +(parentID:[1393 TO 1393]) +(sfTitle:bedrijfsinformatie*^10.0) (sfJobCategories_nodeNames_nl:bedrijfsinformatie*^8.0) (sfAccountName_nodeNames_nl:bedrijfsinformatie*^6.0) (contents_nl:bedrijfsinformatie*^4.0 contents:bedrijfsinformatie*^4.0) }': Encountered " "TO" "LuceneQuery: "" at line 1, column 21.
Was expecting one of:
    "]" ...
    <RANGEIN_QUOTED> ...
    
 ---> Lucene.Net.QueryParsers.Classic.ParseException: Encountered " "TO" "LuceneQuery: "" at line 1, column 21.
Was expecting one of:
    "]" ...
    <RANGEIN_QUOTED> ...
```

Any more ideas are welcome :-)
Thanks in advance!

**Comment by Sven883** [comment]
@nikcio would there be more options when using examine 3 with umbraco 10?
We don't want to switch our queries to nativeQueries.

**Comment by Shazwazza** [comment]
I would suggest determining the bare minimal query that fails like @nikcio. I would also suggest starting your tests by cloning this repo and trying to write a unit test for this. 

On another note, boosting and wildcard combination is not normally allowed by Lucene. More info here https://stackoverflow.com/questions/10352404/lucene-net-boost-not-working-when-using-wildcard

You can also search this repo for `SetMultiTermRewriteMethod` and you'll see that there is mention of using this already.

In the `ErrorCheckingScoringBooleanQueryRewrite` it has a description: https://github.com/Shazwazza/Examine/blob/release/3.0/src/Examine.Lucene/Providers/ErrorCheckingScoringBooleanQueryRewrite.cs 

This isn't enabled by default but it could be, though you have to cast your queries down to the Lucene classes.

There's also this commented out code here with comments in `BaseLuceneSearcher`: https://github.com/Shazwazza/Examine/blob/release/3.0/src/Examine.Lucene/Providers/BaseLuceneSearcher.cs#L62
