### ISSUE TITLE
Escaped value returns no results when it should

### ISSUE THREAD

**Issue by dealloc** [Shazwazza/Examine#325]
I'm dynamically building a query from parameters using the following function:
```csharp
private IBooleanOperation BuildFacetFromList(IQuery query, List<string> facets, string field)
{
	if (facets.Count == 1)
		return query.Field(field, facets.First().Escape());

	return query.Group(group =>
	{
		var operation = group.Field(field, facets.First().Escape());
		return facets
			.Skip(1)
			.Aggregate(operation, (current, facet)
				=> current.Or().Field(field, facet.Escape())
			);
	});
}
```
When I run this code it results in a query something like this: ```+Language:fr +ContractType:"Intérimaire option contrat fixe"```
![image](https://user-images.githubusercontent.com/2164354/211202721-96da416d-8cf5-4246-befa-14de80c5f5d2.png)
However, running this query using Examine gives me this:
![image](https://user-images.githubusercontent.com/2164354/211202745-1f1d0ce5-5eee-4628-b657-0637e2fc43d4.png)
Whereas there's definitely results in the index that should match this query, which can be demonstrated by running the stringified query in the interface:
![image](https://user-images.githubusercontent.com/2164354/211202791-3cb5a682-b410-472d-9cad-9c9c30fd7ae9.png)
or even feeding it to the `NativeQuery` method:
![image](https://user-images.githubusercontent.com/2164354/211202989-63c80078-fa08-4105-844a-964fd874e177.png)

I'm using `Escape` since (as seen in the screenshots) some parameters are multiple words but should be treated as a single term (otherwise irrelevant results are shown as well.

The field is indexed as `FieldDefinitionTypes.FullText` and has `new StandardAnalyzer(LuceneVersion.LUCENE_48)` as it's analyzer.

Currently my workaround is to take the string version and feed it to the parser again, but that feels like a hacky workaround I'd very much like to get rid of.

**Comment by mistyn8** [comment]
Having hit the issue myself and trying to create a failing test, NativeQuery doesn't leave your string input alone as you might think.
If you take a look at the raw query that NativeQuery generates I think you'll find that it's lowercased.. whereas `Escape()` will leave it upper case.
(lower casing being key for the phrase to match against the index??)

**Comment by Shazwazza** [comment]
Escape() has a particular nuance, it is meant to be an exact match, not specifically a phrase, however, here's a proposed change https://github.com/Shazwazza/Examine/issues/329#issuecomment-2168484838

I will close this and continue the discussion there.
