### ISSUE TITLE
Allow settings parentNodeId per content type

### ISSUE THREAD

**Issue by mattbrailsford** [Shazwazza/Examine#33]
Currently on an indexer, you can set a parentNodeId, however the umbraco content indexer can index both content and media so it's impossible to set a parentNodeId that is relevant for both. We should be allowed to set one per content type.

**Comment by Shazwazza** [comment]
This is more of an Umbraco thing, not really an examine thing.

That will start to make the config even uglier. I think this could be feasible by using events for more granular control?

**Comment by mattbrailsford** [comment]
Ahh, sorry, my mistake. But yea, if there was an ability to hook into an event, that would be great.

**Comment by Shazwazza** [comment]
Hey @mattbrailsford happy to discuss the event options you want here - whether its a umb or examine change or just info, it's fine here :)

**Comment by mattbrailsford** [comment]
Whoop! :)

So yea, the Parent ID is one event, having an ability to hook in and set the start node dynamically. The other I needed was having an early, cancelable event for a node being indexed. Right now, the only place you cancel an item from going into the index is within DocumentWriting, but by this point all the processing of that node has occured which is a waste of resources. We could do with an event really early to say "should I bother doing anything with this node?"

**Comment by Shazwazza** [comment]
There is a `NodeIndexing` even that is cancelable, does that one help?
