### ISSUE TITLE
Any plan to release new Version

### ISSUE THREAD

**Issue by croban** [Shazwazza/Examine#352]
I saw in default branch that there is SearchAfterOptions which I will need, but does not exists on v.3.1.0.
Any plan to release this feature?

**Comment by Shazwazza** [comment]
Yes some releases are coming up soon. 3.2 and 4 beta

**Comment by Shazwazza** [comment]
This was just pushed https://github.com/Shazwazza/Examine/releases/tag/v3.2.0-beta.9

Please provide any feedback on the beta if you have any, then can get a main release out sooner.
