### ISSUE TITLE
Sorting and paging highlight same both menu items

### ISSUE THREAD

**Issue by bjarnef** [Shazwazza/Examine#359]
It noticed when accessing Sorting or Paging both menu items are highlighted:
https://shazwazza.github.io/Examine/articles/sorting.html

![image](https://github.com/Shazwazza/Examine/assets/2919859/3cf12a7a-09df-47da-bd24-c2b59bc0ff4e)

I guess it is because it is same page and Paging just links to an anchor:
https://shazwazza.github.io/Examine/articles/sorting.html#paging-and-limiting-results

Maybe Paging should be moved to a separate page instead?
https://shazwazza.github.io/Examine/articles/paging.html

The 404 page looks a bit odd 😁
https://shazwazza.github.io/Examine/articles/test.html

![image](https://github.com/Shazwazza/Examine/assets/2919859/aefbf70b-b490-4167-8515-e7a98e229e9c)

**Comment by Shazwazza** [comment]
Thanks for the report. @nzdev knows all about how this is put together but if you know how this can be fixed a PR would be very helpful!

**Comment by nzdev** [comment]
Not too sure about the 404 page appearance, PR's welcome. 

Sorting and paging are strongly linked concepts. I added a link to paging to the menu to make it easier to find.

**Comment by bjarnef** [comment]
Yeah, just think it may be better to move paging to a separate page instead? Which I guess would solve the double highlight in the navigation.

**Comment by nzdev** [comment]
Location of sort + page wsa unchanged from the original Jekyll docs site. Over to @Shazwazza to decide if it should move, I don't mind either way. I think splitting out doc pages might help with discover-ability.

**Comment by bjarnef** [comment]
Another issue with this is the footer navigation from 
https://shazwazza.github.io/Examine/articles/sorting.html

![image](https://github.com/Shazwazza/Examine/assets/2919859/1b265320-3638-4344-a2ae-b2af1b806d88)

from here in goes to
https://shazwazza.github.io/Examine/articles/sorting.html#paging-and-limiting-results

but still show it at last step, unlike [Configuration](https://shazwazza.github.io/Examine/articles/configuration.html) which doesn't  show a first step.

![image](https://github.com/Shazwazza/Examine/assets/2919859/e6970e69-ac47-430c-88bc-9aa3d8a4376b)

**Comment by nzdev** [comment]
See https://github.com/Shazwazza/Examine/pull/361
