### ISSUE TITLE
Synchronous indexing

### ISSUE THREAD

**Issue by jakoss** [Shazwazza/Examine#368]
I'm creating a small console app that will create an index, that's all what this app does. For this build index synchronously would be just perfect for me, but i cannot understand how to do that. Docs are saying about `ProcessNonAsync` method, but such method does not exist. Is there any other way to do that?

**Comment by Shazwazza** [comment]
Depending on the version you are using I think this has changed, see: https://github.com/Shazwazza/Examine/blob/03d208b50bf7be6133f5c531138f8b4549d2e10a/src/Examine.Test/Examine.Lucene/Index/LuceneIndexTests.cs#L529

Example: 

using (customIndexer.WithThreadingMode(IndexThreadingMode.Asynchronous))

It used to be a ProcessNonAsync method

**Comment by jakoss** [comment]
Ok, if somebody will be trying to figure it out in the future, here is what's required when using `IExamineManager`:

```csharp
using var index = (examineManager.GetIndex("GtpCodeIndex") as LuceneIndex)!;
using var syncIndex = index.WithThreadingMode(IndexThreadingMode.Synchronous);
```

@Shazwazza does this seem fine or is there better way to approach that?

**Comment by Shazwazza** [comment]
Yep I think that is good, the cast would have been needed before anyways. The Examine abstraction doesn't force background (async) or non-async indexing processing so a cast is needed to the implementation.

**Comment by jakoss** [comment]
Now it's clear, but honestly it's a bit confusing at start. From docs it's not really that clear how to make sure that everything is indexed. Looking at the code `IndexOperationComplete` might be called multiple times if there is some time gap between adding new `IndexItems`, is that correct?

Thanks for quick responses :)

**Comment by Shazwazza** [comment]
Always happy for any contrib to the docs :)

That callback will indeed be called differently depending on how many items are indexed at once, or time gaps in between.

Indexing synchronously isn't really ideal, so guess it depends on what you are doing?

**Comment by jakoss** [comment]
I guess the default behavior, asynchronous, works fine for long-running processes. But sync might be better if indexing is all the application is doing. I want to just build the index and end the process. So it's crucial for me that all of the data is commited and flushed properly.

I'll create a pull request with docs updater later

**Comment by Shazwazza** [comment]
okidoke sounds good! Just want to make sure you're using it for the right use case :)

**Comment by jakoss** [comment]
@Shazwazza I created PR for this
