### ISSUE TITLE
Query by Id does not return search result

### ISSUE THREAD

**Issue by jakoss** [Shazwazza/Examine#370]
I'm trying to do a simplest query by item id. Using this code:

```csharp
var existingItem = index.Searcher.CreateQuery()
            .Id(fileId)
            .Execute();
```
But i have empty results. Then, when i access the searched object by searching through fields:
```csharp
var theSameItemButUsingFields = index.Searcher.CreateQuery()
            .Field("relative_path", relativePath)
            .And()
            .Field("hash", fileHash)
            .Execute();
```
I have proper result and the returned item has proper `fileId` set. So it is there, is has the expected id, but the first query does not return it properly. Am I doing something wrong here? `fileId` is just a string

**Comment by Shazwazza** [comment]
The .Id query is querying on __Node Id which is the document Id, is that how you are indexing the document?

Here's a working example in the tests

https://github.com/Shazwazza/Examine/blob/56c89711b6e6d60d143b162068fdb774857b7052/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L2204

**Comment by jakoss** [comment]
I was using the id field during indexing, so it should work. And for example - deletes by id worked correctly, but queries did not.

Either way - for multiple reasons we decided to move to "bare" Lucene.net, we need more granular control over our indexes. So we can close this i think

**Comment by Shazwazza** [comment]
Ok thanks for the update. Not sure why Id wasn't working for you, that seems very strange. Also note that you can get direct access to the underlying Lucene APIs via Examine by casting the index to LuceneIndex which gives you access to the underlying Lucene APIs.

**Comment by jakoss** [comment]
> Also note that you can get direct access to the underlying Lucene APIs via Examine by casting the index to LuceneIndex which gives you access to the underlying Lucene APIs. 

We were using that so much that keeping examine as a passthrough didn't make much sense for us 😁

**Comment by Shazwazza** [comment]
fair enough :)
