### ISSUE TITLE
RebuildOnAppStart removed - it will be up to the application to rebuild if necessary

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#38]

**Comment by CasperTDK** [comment]
Seems like a bad idea. A complete rebuild can take over 10 minutes for our bigger customers  (60k+ nodes). We do not want huge downtime every time we release a new version of the website.

**Comment by Shazwazza** [comment]
I don't know what you mean. Why would you have downtime on every release?

All this is saying is that Examine will not rebuild your indexes  on startup if they don't exist - which is what it does now unless you turn this option off. In v2.0 it would be up to the application using Examine to rebuild an index on startup based on it's own rules, this would not be the responsibility of Examine.

**Comment by CasperTDK** [comment]
Sorry. I have misunderstood the feature. I believed that examine would determine in V2 whether or not it should rebuild the index - which is a slow process for bigger websites.
It is just fine, if it is up to the application.
