### ISSUE TITLE
Examine and lucene version

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#396]
Hi Shannon,
There is issue with lucen.net 4.8.0 beta 16, which is high vulnerability:
https://github.com/advisories/GHSA-2qw8-ppr5-m96c
It is resolve in beta 17, but beta 17 contains a lot breaking changes, can you look into how many of them we can workaround or fix for it can be only in v4?
https://github.com/apache/lucenenet/releases/tag/Lucene.Net_4_8_0_beta00017

**Comment by Shazwazza** [comment]
It's not really a high vulnerability but either way, you can just update and examine will continue to work

**Comment by Shazwazza** [comment]
I'll ship a new targeted examine version this week

**Comment by NijasHameed** [comment]
@Shazwazza So regadless of umbraco or lucene version, I can just update this Lucene.Net.Replicator package to Lucene.Net.Replicator --version 4.8.0-beta00017, 
FYI: my umbraco version is 13.5.2. and examine is 3.3.0

**Comment by Shazwazza** [comment]
Yes.

Will be releasing a 3.5 version targeting the new lucene release soon.
