### ISSUE TITLE
Problem on Umbraco 13

### ISSUE THREAD

**Issue by afabri73** [Shazwazza/Examine#398]
Hi,
I'm using Umbraco 13 and I actually have the following code:

```
string[] queryFields = { "title", "abstract", "articleTags" };

var queryResult = index.Searcher
.CreateQuery("content")
.NodeTypeAlias("article")
.And()
.GroupedOr(queryFields, $"*{query}*")
.Execute();
```
This code retrieves all articles that have the exactly search term.
What I need, instead, is to find all articles that exactly or partially match the query term.

For example, searching "dona", I expect to find 14 results (6 articles that have "dona" in query fields and other 8 articles that have "donazione" or "donatore" in query fields)
Currently, instead, I find only 6 articles that have exaclty "dona" in query fields.

What am I doing wrong?
Thank you for the support
Adriano

**Comment by Shazwazza** [comment]
Lucene by default does not support leading wildcards which your query indicates that are you trying. Leading wildcards can cause significant performance penalties.

Umbraco does enable this on the content delivery API but that is it (see https://github.com/umbraco/Umbraco-CMS/blob/a72ffc8542d0ea5f44870a810c087dc9d3ccb9b9/src/Umbraco.Cms.Api.Delivery/Services/QueryBuilders/ApiContentQueryFactory.cs#L21)

For other examples and documentation for querying with examine, see:

* https://shazwazza.github.io/Examine/articles/searching.html
* https://github.com/Shazwazza/Examine/blob/release/3.0/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs
