### ISSUE TITLE
Issue in Italian PC

### ISSUE THREAD

**Issue by fspezi** [Shazwazza/Examine#5]
I look that when the indexing process is running in "it-IT" culture, and when the data to indexing contains datatypes like Double, Lucene fires an Exception.

I found the row code where it is happen:  
`Examine.LuceneEngine.Providers.LuceneIndexer.TryConvert<T>(string var, out object parsedVal)` merhod.

The `tc.ConvertFrom(val)` row try to convert `val` string to `T` type. If `T` is Double or Float, and if `val` contains decimal digits (like "1234.567"), the method can't convert to `T` because the DOT char is not the decimal separator in "it-IT" culture.

I think that I have the solution.  
I look that this code solve the issue:  
`parsedVal = (T)tc.ConvertFrom(null, System.Globalization.CultureInfo.InvariantCulture, val);`

Is this a good solution? Is it possible to apply this patch in Examine?

Thanks

**Comment by Shazwazza** [comment]
I thanks for this, will apply this to next release (coming very soon)
