### ISSUE TITLE
Published node with pending changes are not included when examine rebuilds?

### ISSUE THREAD

**Issue by paulosamson** [Shazwazza/Examine#63]
Hi we have this issue where the nodes that were published but "with pending changes" went missing after examine rebuilds its index. 

Please see this video: http://www.screencast.com/t/v6jBzbVjZZ
In the video I saved 'testpage' node then rebuilt the index. After that it was gone from the search tool.

**Comment by Shazwazza** [comment]
This is an Umbraco issue not an Examine issue, can you please post on the Umbraco tracker: http://issues.umbraco.org

In the meantime you haven't mentioned what versions you are using - we'd need to know both Umbraco and Examine versions

**Comment by paulosamson** [comment]
Thanks I'll post it there. 

I'm using latest umbraco version 7.5.6 and examine is 0.1.70.0

**Comment by Shazwazza** [comment]
Thanks, I've related that to another issue - which might be the same problem. I'll close this here and we'll look into the issue on the tracker next sprint.
