### ISSUE TITLE
Not all content indexed when using supportUnpublished="true" and content type has more than 10k nodes

### ISSUE THREAD

**Issue by mahgo** [Shazwazza/Examine#70]
Only roughly 9.9k nodes out of the roughly 35k of the particular content type are indexed, when using supportUnpublished="true" and setting IncludeNodeTypes to one content type. When supportUnpublished="false", all 36k or so nodes (of all content types) are successfully indexed.

From looking at the code, the issue is most likely located in UmbracoExamine.DataServices.UmbracoContentServiceGetLatestContentByXPath(string), but am unable to get a pdb that will work with the 0.1.70.0 Nuget package I'm using to test this.

**Comment by Shazwazza** [comment]
This is an umbraco issue not an examine issue please log the issue with steps to reproduce, and the umbraco version you are using, you will also need to test that you can reproduce with the latest umbraco version. 
You can post this umbraco issue link here if you want me to have a look.

**Comment by mahgo** [comment]
I'll try test it into further detail. Do you know how I can replace the Examine nuget package with a build of my own? (as Umbraco depends on the Examine package)

**Comment by mahgo** [comment]
I've made an issue here: http://issues.umbraco.org/issue/U4-9398
I've also made a pull request with a fix: https://github.com/umbraco/Umbraco-CMS/pull/1695

**Comment by Shazwazza** [comment]
Great thanks! I'll have a look now.
