### ISSUE TITLE
In searchresults make _topDocs public

### ISSUE THREAD

**Issue by ismailmayat** [Shazwazza/Examine#77]
Shannon,

Any issues with making  private TopDocs _topDocs; in Examine.LuceneEngine.SearchResults public like query and searcher? Reason I ask is I have been trying to use highlighter.net to no avail. I am now trying to use FastVectorHighlighter from lucene.net contrib however that requires TopDocs object.

I can do it and make pull request.

Regards

Ismail

**Comment by Shazwazza** [comment]
Hi mate,

Yes please send any PR that you think will be required and we can review/discuss from there.

**Comment by ismailmayat** [comment]
Shannon,

Done and created PR.

Regards

Ismail
