### ISSUE TITLE
Reference to AzureDirectoryNativeLockFactory which isn't an available class

### ISSUE THREAD

**Issue by tmoxon** [Shazwazza/Examine#79]
Just pulled v1.8.2 and the change from AzureDirectoryLockFactory to AzureDirectoryNativeLockFactory causes build failure as the latter doesn't exist. Perhaps a missing file from the related changes?

Doesn't affect my build so I've reverted that, but needs attention at some point.

Thanks

**Comment by Shazwazza** [comment]
yup sorry that code is in flux, you can easily just unload that azure project if you want, i'll fix up soon.

**Comment by Shazwazza** [comment]
should be building again with latest commits
