### ISSUE TITLE
Is GroupedAnd correct?

### ISSUE THREAD

**Issue by samgooch** [Shazwazza/Examine#91]
If you take a look at the test "GROUPED AND - SINGLE FIELD, MULTI VAL"...

Shouldn't the output be...

`+__NodeTypeAlias:mydocumenttypealias +(+id:1 +id:2 +id:3)`

Otherwise, why bother specifying more field values than there are fields? The same applies with the other scenarios such as multi-field and multi-values. It should generate all permutations?

Or have I misunderstood what this method is supposed to be doing? To me it should behave like the GroupedOr does except it should have the "+" symbol in front of each field:value.

**Comment by TomSteer** [comment]
The test comment explains why that is the case:

```
        /// <summary>
        /// Grouped AND is a special case as well since NOT and OR include all values, it doesn't make
        /// logic sense that AND includes all fields and values because nothing would actually match. 
        /// i.e. +id:1 +id2    --> Nothing matches
        /// </summary>
```

**Comment by samgooch** [comment]
That makes sense for an ID field. But for my scenario I am searching in a string to see whether it contains two words. For example, the field "name". I want to search for "black" and "tee". Does that make sense?

**Comment by Shazwazza** [comment]
Sorry for the very long delay here :( I'll look at this tomorrow and get a new release out. It's been a long time since looking at this but yeah it was probably based on the assumption of an ID type field but of course you could have a query like +(+name:Shannon +name:Deminick) meaning that name must contain both

**Comment by samgooch** [comment]
I've raised a PR for this - see https://github.com/Shazwazza/Examine/pull/111

**Comment by Shazwazza** [comment]
Thanks, i have this starred in my inbox and will have a look as soon as i can!

**Comment by Shazwazza** [comment]
Have merged this in and fixed up tests, turns out there was one other minor bug with the Grouped stuff too. Should all be resolved and makes sense. Thanks a ton, i'll get a release out asap!

**Comment by Shazwazza** [comment]
now in release https://github.com/Shazwazza/Examine/releases/tag/v0.1.90
