### ISSUE TITLE
Can I sort by custom field without creating new index?

### ISSUE THREAD

**Issue by Andrei-** [Shazwazza/Examine#92]
I have publishDate field on news items. I'm using ExternalSearcher to fetch results and I would like to sort them by this field. Doesn't work.

My last attempt was to problematically enable sorting on that field on app started:

`var websiteIndexer = (UmbracoContentIndexer)ExamineManager.Instance.IndexProviderCollection["ExternalIndexer"];
            foreach (var field in websiteIndexer.IndexerData.UserFields)
            {
                if (field.Name == "publishDate")
                {
                    field.EnableSorting = true;
                }
            }` 

and then manually add the sorting decorator field on publish:

`                    NumericField fldSorting = new NumericField("__Sort_publishDate", Field.Store.YES, true);
                    fldSorting.SetLongValue(long.Parse(date.ToString("yyyyMMddHHmmss")));
                    e.Document.Add(fldSorting);`

Also tried adding custom user field to ExternalIndexSet, but doing that wipes out all other fields.

**Comment by Shazwazza** [comment]
Hi,

Yeah, unfortunately you've hit one of the issues I'd like to fix. To have a field marked as sortable, you have to declare it sortable in the config, but by doing that it means that your index now has to declare all of the fields it wants to index explicitly which isn't ideal. 

So what I'd like to do is:

* Allow for programatically making a field sortable
* Allow for marking a field sortable in the config but not have to explicitly define all fields - this would require some sort of attribute on the fields like fieldInclusion="explicit|all|auto" 
   * "auto" is what we have today, when no fields are defined, than "all" fields are indexed, but if one or more fields are defined, than only those fields are indexed
   * "explicit" - only index what fields are defined
   * "all" - index all fields regardless of what fields are defined

**Comment by amv-** [comment]
Hi Shannon,
I actually managed to make it work using the approach in the first post. It takes two steps I think:

First In Umbraco startup events - ApplicationStarted override method, I programatically enable sorting on the field:

`            var websiteIndexer = (UmbracoContentIndexer)ExamineManager.Instance.IndexProviderCollection["ExternalIndexer"];
            
            foreach (var field in websiteIndexer.IndexerData.UserFields)
            {
                if (field.Name == "publishDate")
                {
                    field.EnableSorting = true;
                }
            }
           websiteIndexer.DocumentWriting += websiteIndexer_DocumentWriting; 
`
Then I use DocumentWriting event to programatically add a sorting field for my publishDate field called __Sort_publishDate:

`
        void websiteIndexer_DocumentWriting(object sender, Examine.LuceneEngine.DocumentWritingEventArgs e)
        {

            // replace "grid" field with searchable text
            string nodeTypeAlias = e.Fields["nodeTypeAlias"];
            if (nodeTypeAlias.ToLower().EndsWith("page"))
            {

                if (e.Fields["nodeTypeAlias"].EqualsIgnoreCase("UmbNewsPage"))
                {
                    var date = DateTime.MinValue;
                    if (!DateTime.TryParse(e.Fields["publishDate"], out date))
                    {
                        date = DateTime.MinValue;
                    }

                    NumericField fldSorting = new NumericField("__Sort_publishDate", Field.Store.YES, true);
                    fldSorting.SetLongValue(long.Parse(date.ToString("yyyyMMddHHmmssfff")));

                    e.Document.Add(fldSorting);
                }
          }
     }
`
I can't remember for sure if manually adding __Sort_publishDate is necessary, I think it is.

Then when searching, I order using this: 
OrderByDescending(new SortableField("publishDate", SortType.Long));

**Comment by mistyn8** [comment]
This was invaluable.. I actually found that I didn't need the document writing part..
simply updating the umbracoBytes to DOUBLE and sortable, and then reindexing via examinemanagement console was enough.

```
    protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
    {
        var websiteIndexer = (UmbracoContentIndexer)ExamineManager.Instance.IndexProviderCollection["InternalIndexer"];

        foreach (var field in websiteIndexer.IndexerData.UserFields)
        {
            if (field.Name == "umbracoBytes")
            {
                field.Type = "DOUBLE";
                field.EnableSorting = true;
            }
        }       
    }
```

front end listing..
```
    var searcher = Examine.ExamineManager.Instance.SearchProviderCollection["InternalSearcher"];
    var sc = searcher.CreateSearchCriteria("media");
    var sc1 = sc.ParentId(6789).And().OrderBy(new SortableField("umbracoBytes", SortType.Double)).Compile();


    var sr = searcher.Search(sc1);
    <ul>
        @foreach (var result in sr)
        {
            <li>
                @(result.Fields["nodeName"])
                @(result.Fields["updateDate"])
                @(result.Fields["umbracoBytes"]))
            </li>
        }
    </ul>
```

thank you for sharing!

**Comment by Shazwazza** [comment]
I'll close this issue since this is for an old version. Glad everyone figured out a work around. In the 1.x version changing field types and sortability is much easier.
