### ISSUE TITLE
Possible to pass list to .NodeTypeAlias()

### ISSUE THREAD

**Issue by TheBekker** [Shazwazza/Examine#93]
I find my self missing to be able to pass a list of NodeTypeAliases to filter down a search, that would also make a dynamic change of NodeTypeAlias much easier.

A ..GroupedOr()/.GroupedAnd() could be a possibility, but then analyzers seem to mess with the values?

I would gladly take a swing at a PR for this, but just wanna make sure that there is not something im missing here?

**Comment by StefanFrederiksen** [comment]
I would love this use case as well, for now I am circumventing it by doing 

`.And().GroupedOr(new[] { "nodeTypeAlias" }, new[] { "nodeType1", "nodeType2", ... })`

But giving a list to .NodeTypeAlias() would be more intuitive.

**Comment by Shazwazza** [comment]
It would be pretty easy to just create an extension method to perform the same thing as you've just written there :) 
If anyone is able to submit a PR for that i can have a look as soon as i can.

**Comment by TheBekker** [comment]
I havent look closely at the code, but does the NodeTypeAlias just add a normal field query?
Cause if i dont remember wrong, it seems that field queries and GroupedOr/And seem to have their values affected by stemming and analyzer, where NodeTypeAlias does not?

**Comment by TheBekker** [comment]
Im guessing this has something to do with it:

NodeTypeAliasInternal()
`//don't use the query parser for this operation, it needs to match exact
       return this.FieldInternal(NodeTypeAliasField, eVal, occurance, false);`

**Comment by TheBekker** [comment]
Made a pull request that should fix this.
https://github.com/Shazwazza/Examine/pull/96
