### ISSUE TITLE
OrderBy(Descending) multiple options

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/Examine#97]
The sorting Wiki page only details how to sort on a single field.

Question: How do I sort on score and then on updateDate and then on nodeName?

Is there OrderBy().ThenBy() support?
or do we have to generate a sort object to pass into the OrderBy method?

cheers.

**Comment by Shazwazza** [comment]
You cannot sort on score and by something else, that's not the way Lucene works underneath. In fact if you sort on anything but score, you'll notice the score value is the same across all results.

I'm gonna try to follow up on the latest questions in this repo today/tomorrow (sorry for the delay!) so will get back to you re: sorting on multiple fields.

**Comment by NikRimington** [comment]
Hey @Shazwazza is this still the case on the latest version of Examine?

So it wouldn't be possible to sort based in the Created Date and then by Score? 

Slightly off the primary topic of this, but how can you sort by score Ascending instead of Descending (which seems to be the default) ?

**Comment by Shazwazza** [comment]
Latest version (1.x) you can do `OrderByDescending` and you can chain OrderBy's 

so you could do 

```cs
searcher.CreateQuery()
   .Field("writerName", "administrator")
   .OrderByDescending(new SortableField("nodeName", SortType.String))
   .OrderBy(new SortableField("somethingElse", SortType.String))
```

will close this now and assign to the 1.0 release

**Comment by Shazwazza** [comment]
But to answer further with Score 

> So it wouldn't be possible to sort based in the Created Date and then by Score?

Right now in Examine i don't think you can do this but i think it's possible to implement a "Score" + another field option, though that might require breaking an interface.
