### ISSUE TITLE
RawQuery is unescaped

### ISSUE THREAD

**Issue by mellson** [Shazwazza/Examine#99]
When I try to do a raw query like so:
`var searchCriteria = searcher.CreateSearchCriteria().RawQuery(luceneString);`

Then my luceneString is unescaped. If I have a string containing for instance `3\\-A` then that is changed to `3-a`.

Is there a way to keep the escapes?

**Comment by Shazwazza** [comment]
This is a Lucene thing IIRC. When you pass a string to RawQuery it uses Lucene's QueryParser to parse it into a query. A backslash is an escape char for a lucene query, so try adding a backslash before each char you need to escape (maybe 3\\\\\-A) you can also try the Escape method of the query parser https://lucene.apache.org/core/2_9_4/api/core/org/apache/lucene/queryParser/QueryParser.html#escape(java.lang.String)

**Comment by mellson** [comment]
Thanks for the reply! I got it working when I realised that I had introduced a single backslash into the index content 🤦‍♂️ When I removed that I could use your escape helper or the Lucene helper to build the query I wanted. Thanks for your help 🙏
